Adding locking

diff --git a/local-bin/save-pkgstates b/local-bin/save-pkgstates
--- a/local-bin/save-pkgstates
+++ b/local-bin/save-pkgstates
@@ -1,6 +1,14 @@
 #!/bin/bash
 # CRONTAB: 29   * *   *   *     /usr/bin/sudo /usr/local/bin/save-pkgstates
-BASEDIR="/etc/package-states.apt+dpkg"
+for tool in rm dirname readlink mkdir file dpkg apt-mark; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
+LOCKFILE="${TMPDIR=/tmp}/${CURRABSPATH//\//_}${0##*/}.lock"
+if ! (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
+	echo -e "${cR}ERROR:${cZ} Lock failed, PID $(cat "$LOCKFILE") [$LOCKFILE]" >&2
+	exit 1
+fi
+trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
+BASEDIR="/etc/package-states.apt_and_dpkg"
 DPKG="/usr/bin/dpkg"
 APTMARK="/usr/bin/apt-mark"
 EXTSTATES="/var/lib/apt/extended_states"
