Adjustments to the scripts

diff --git a/svnsync/sync b/svnsync/sync
--- a/svnsync/sync
+++ b/svnsync/sync
@@ -3,7 +3,7 @@
 [[ -n "$DEBUG" || -n "$DBG" ]] && set -x
 CURRABSPATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) # Get the directory in which the script resides
 LOCKFILE="$CURRABSPATH/.lock"
-for tool in 7z svn svnsync svnadmin; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in 7z nice sha1sum svn svnsync svnadmin tee; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 if (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
 	trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
 	function show_time_diff
@@ -39,7 +39,8 @@ if (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
 			trap 'echo "Cleaning up ${FNAME##*/} due to error or interrupt."; rm -f "$LOCKFILE" "$DUMPNAME" "$ARCHNAME"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
 			svnadmin dump -r $REV0:$REVNO --deltas --incremental "$CURRABSPATH" > "$DUMPNAME" && \
 				ls -ld "$DUMPNAME" && \
-				7z a -t7z -y -mx9 -m0=lzma2 -ms=on "-w${DUMPNAME%/*}" "$ARCHNAME" "$DUMPNAME" && \
+				nice 7z a -t7z -y -mx9 -m0=lzma2 -ms=on "-w${DUMPNAME%/*}" "$ARCHNAME" "$DUMPNAME" && \
+				sha1sum "$DUMPNAME" "$ARCHNAME"|tee "$ARCHNAME.sha1sum" && \
 				rm -f "$DUMPNAME"
 			show_time_diff $TIME_START $(date +%s) "Packaging $FNAME took: %s"
 			trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
