Adding better output

diff --git a/svnsync/sync b/svnsync/sync
--- a/svnsync/sync
+++ b/svnsync/sync
@@ -3,7 +3,7 @@
 [[ -n "$DEBUG" || -n "$DBG" ]] && set -x
 CURRABSPATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) # Get the directory in which the script resides
 LOCKFILE="$CURRABSPATH/.lock"
-for tool in 7z nice sha1sum svn svnsync svnadmin tee; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in 7z awk grep nice sha1sum svn svnsync svnadmin tee; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 if (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
 	trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
 	function show_time_diff
@@ -22,6 +22,7 @@ if (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
 		echo -e "${cB}URL:${cZ} '$(svn propget svn:sync-from-url --revprop -r 0 "file://$CURRABSPATH")'"
 		svn propdel --revprop -r0 svn:sync-lock "file://$CURRABSPATH"
 		svnsync --non-interactive sync "file://$CURRABSPATH" && touch "$CURRABSPATH"
+		svn info "file://$CURRABSPATH"|grep ^Revision:
 	else
 		echo "$CURRABSPATH"
 		REV0=0
@@ -35,7 +36,7 @@ if (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
 			echo -e "${cR}ERROR:${cZ} ${cW}$ARCHNAME${cZ} already exists. Move it out of the way." >&2
 			exit 1
 		fi
-		echo "$FNAME"
+		echo "$ARCHNAME + $DUMPNAME"
 		if [[ ! -e "$ARCHNAME" ]]; then
 			let TIME_START=$(date +%s)
 			trap 'echo "Cleaning up ${FNAME##*/} due to error or interrupt."; rm -f "$LOCKFILE" "$DUMPNAME" "$ARCHNAME" "$ARCHNAME.sha1sum"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
