More robust logic if the script gets killed

diff --git a/svnsync/sync b/svnsync/sync
--- a/svnsync/sync
+++ b/svnsync/sync
@@ -26,6 +26,8 @@ if (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
 		echo "$CURRABSPATH"
 		REV0=0
 		REVNO=$(svn info "file://$CURRABSPATH"|awk '/^Revision:/ {print $2}')
+		REV1000=$((REVNO%1000))
+		REVNO=$((REVNO-REV1000))
 		FNAME="${1//REVNO/rev${REV0}_to_${REVNO}}"
 		DUMPNAME="${FNAME}.svndump"
 		ARCHNAME="${FNAME}.7z"
@@ -34,13 +36,13 @@ if (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
 			exit 1
 		fi
 		echo "$FNAME"
-		if [[ ! -e "$FNAME" ]]; then
+		if [[ ! -e "$ARCHNAME" ]]; then
 			let TIME_START=$(date +%s)
-			trap 'echo "Cleaning up ${FNAME##*/} due to error or interrupt."; rm -f "$LOCKFILE" "$DUMPNAME" "$ARCHNAME"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
+			trap 'echo "Cleaning up ${FNAME##*/} due to error or interrupt."; rm -f "$LOCKFILE" "$DUMPNAME" "$ARCHNAME" "$ARCHNAME.sha1sum"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
 			svnadmin dump -r $REV0:$REVNO --deltas --incremental "$CURRABSPATH" > "$DUMPNAME" && \
 				ls -ld "$DUMPNAME" && \
 				nice 7z a -t7z -y -mx9 -m0=lzma2 -ms=on "-w${DUMPNAME%/*}" "$ARCHNAME" "$DUMPNAME" && \
-				sha1sum "$DUMPNAME" "$ARCHNAME"|tee "$ARCHNAME.sha1sum" && \
+				( cd "${FNAME%/*}" && sha1sum "${DUMPNAME##*/}" "${ARCHNAME##*/}"|tee "${ARCHNAME}.sha1sum" ) && \
 				rm -f "$DUMPNAME"
 			show_time_diff $TIME_START $(date +%s) "Packaging $FNAME took: %s"
 			trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
