Having trouble with SO_PRIORITY

diff --git a/build-scripts/build-dropbear b/build-scripts/build-dropbear
--- a/build-scripts/build-dropbear
+++ b/build-scripts/build-dropbear
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-for tool in rm rmdir dirname readlink file tempfile grep tee git date make gcc wget tar md5sum autoconf autoheader; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in rm rmdir dirname readlink file tempfile grep tee git date make gcc wget tar md5sum sed autoconf autoheader; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 ( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBGCONFIGURE="$SHELL -x "; set -x; }
 MEANDMYSELF=${0##*/}
@@ -145,7 +145,6 @@ echo -e "Configuring and building ${cW}zlib${cZ}"
 ) || { echo -e "${cR}ERROR:${cZ} zlib failed to build."; exit 1; }
 echo -e "Configuring and building ${cW}dropbear${cZ}"
 (
-	export CC="$CC -nostdinc -isystem $TEMPDIR/musl/tempinstall/include -isystem /usr/include/$(gcc -dumpmachine) -isystem /usr/include"
 	cd "$PRJSRCDIR" && \
 		autoconf && autoheader && \
 	cd "$BUILDDIR" && \
@@ -161,5 +160,4 @@ echo -e "Configuring and building ${cW}dropbear${cZ}"
 
 
 exit 0
-
-[[ -n "$NO_REMOVE_TEMPDIR" ]] || rm -rf "$TEMPDIR"
+		sed -i 's|ifdef SO_PRIORITY|#ifdef SO_PRIORITY\n#undef SO_PRIORITY\n#endif\nif 0|g' $PRJSRCDIR/includes.h && \
