Refining the scripts

diff --git a/build-scripts/build-musl b/build-scripts/build-musl
--- a/build-scripts/build-musl
+++ b/build-scripts/build-musl
@@ -106,7 +106,7 @@ while getopts "h?t:i:vV:" opt; do
 	esac
 done
 if ! (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
-	echo -e "${cR}ERROR:${cZ} Lock failed, PID $(cat "$LOCKFILE")" >&2
+	echo -e "${cR}ERROR:${cZ} Lock failed, PID $(cat "$LOCKFILE") [$LOCKFILE]" >&2
 	exit 1
 fi
 trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
diff --git a/build-scripts/build-ninja b/build-scripts/build-ninja
--- a/build-scripts/build-ninja
+++ b/build-scripts/build-ninja
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-for tool in rm rmdir dirname readlink file tempfile grep tee git date make gcc python; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in rm rmdir dirname readlink file tempfile grep tee git date make gcc python install; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 ( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBGCONFIGURE="$SHELL -x "; set -x; }
 LOCKFILE="${TMPDIR=/tmp}/${CURRABSPATH//\//_}${0##*/}.lock"
@@ -97,7 +97,7 @@ while getopts "h?i:vV:" opt; do
 	esac
 done
 if ! (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
-	echo -e "${cR}ERROR:${cZ} Lock failed, PID $(cat "$LOCKFILE")" >&2
+	echo -e "${cR}ERROR:${cZ} Lock failed, PID $(cat "$LOCKFILE") [$LOCKFILE]" >&2
 	exit 1
 fi
 trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
@@ -119,7 +119,8 @@ trap 'rm -f "$LOCKFILE"; echo -e "'"${cW}INFO:${cZ}"' Removing the build directo
 echo -e "Configuring and building ${cW}$PRJ${cZ}"
 (
 	cd "$BUILDDIR" && \
-		$DBGCONFIGURE"$PRJSRCDIR/configure.py" --bootstrap
+		$DBGCONFIGURE"$PRJSRCDIR/configure.py" --bootstrap && \
+		install -m 755 -vpsD $PRJNAME "$INSTALL_TO/bin/$PRJNAME"
 ) || { echo -e "${cR}ERROR:${cZ} $PRJ failed to build."; exit 1; }
 let TIME_END=$(date +%s)
 show_time_diff $TIME_START $TIME_END      "Overall runtime:     %s (m:ss) with $PM parallel job(s)"
