Several minor improvements

diff --git a/build-scripts/build-dropbear b/build-scripts/build-dropbear
--- a/build-scripts/build-dropbear
+++ b/build-scripts/build-dropbear
@@ -2,9 +2,14 @@
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
 CC_TO_USE=${CROSS_COMPILE}gcc
 ORIG_CC="$CC_TO_USE"
-for tool in rm rmdir dirname readlink file tempfile grep cut tee git date make "${CC_TO_USE}" wget tar sha256sum autoconf autoheader; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in rm rmdir dirname readlink file tempfile grep cut tee git date make "${CC_TO_USE}" wget tar sha256sum autoconf autoheader sed; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 ( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBG=1; DEBUG=1; DBGCONFIGURE="$SHELL -x "; set -x; }
+CROSS_COMPILE_PATH=${CROSS_COMPILE%/*}
+CROSS_COMPILE=${CROSS_COMPILE##*/}
+if [[ -n "$CROSS_COMPILE_PATH" ]]; then
+	export PATH="$CROSS_COMPILE_PATH:$PATH"
+fi
 LOCKFILE="${TMPDIR=/tmp}/${CURRABSPATH//\//_}${0##*/}.lock"
 MEANDMYSELF=${0##*/}
 ZLIBURL="http://zlib.net/zlib-1.2.11.tar.gz"
@@ -105,7 +110,7 @@ if ! (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
 	echo -e "${cR}ERROR:${cZ} Lock failed, PID $(cat "$LOCKFILE") [$LOCKFILE]" >&2
 	exit 1
 fi
-trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
+((DBG)) || { trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT; }
 echo -e "Working directory: $BASEDIR"
 let PM=$(grep -c processor /proc/cpuinfo)
 ((VERBOSE)) && echo -e "${cB}[DBG]${cZ} Number of parallel jobs, based on processor count: $PM."
@@ -135,7 +140,7 @@ else
 	wget -nc -O "$ZLIBPKG" "$ZLIBURL" || curl -o "$ZLIBPKG" "$ZLIBURL" || { echo -e "${cR}ERROR:${cZ} failed to download $ZLIBURL"; exit 1; }
 fi
 echo "$ZLIBSHA256  $ZLIBPKG"|sha256sum -c ||  { echo -e "${cR}ERROR:${cZ} SHA-2 (256-bit) hash does not match!"; exit 1; }
-trap 'rm -f "$LOCKFILE"; echo -e "'"${cW}INFO:${cZ}"' Removing the build directories due to signal."; rm -rf "'$BUILDDIR'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
+((DBG)) || { trap 'rm -f "$LOCKFILE"; echo -e "'"${cW}INFO:${cZ}"' Removing the build directories due to signal."; rm -rf "'$BUILDDIR'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT; }
 ( rm -rf "$BUILDDIR"; mkdir -p "$BUILDDIR/zlib" )
 if echo -n "... unpacking zlib" && tar --strip-components=1 -C "$BUILDDIR/zlib" -xf "$ZLIBPKG" && mkdir -p "$BUILDDIR/zlib/tempinstall"; then
 	echo -e " ${cG}[OK]${cZ}"
@@ -143,10 +148,23 @@ else
 	echo -e " ${cR}[failed]${cZ}"
 	exit 1
 fi
+# Little C program to check which options work to prevent -fPIE -pie etc ...
+HELLOC=$(tempfile -p musl-test -s .c)
+cat > "$HELLOC" <<-'EOF'
+	#include <stdio.h>
+	void main(void)
+	{
+		printf("Hello world!\n");
+	}
+EOF
 # Configure GCC for our purpose
-export CC="$MUSLGCC"
+export CC="$MUSLGCC -static"
 export LDFLAGS="-Wl,--gc-sections -Wl,--hash-style=both"
-export CFLAGS="-ffunction-sections -fdata-sections" # -fnostack-protector
+( set -x; $MUSLGCC -no-pie "$HELLOC" -o "${HELLOC%.c}" ) && NOPIC_FLAGS="${NOPIC_FLAGS+$NOPIC_FLAGS }-no-pie"
+( set -x; $MUSLGCC -fno-pic "$HELLOC" -o "${HELLOC%.c}" ) && NOPIC_FLAGS="${NOPIC_FLAGS+$NOPIC_FLAGS }-fno-pic"
+( set -x; $MUSLGCC -fno-PIC "$HELLOC" -o "${HELLOC%.c}" ) && NOPIC_FLAGS="${NOPIC_FLAGS+$NOPIC_FLAGS }-fno-PIC"
+( set -x; $MUSLGCC -fnostack-protector "$HELLOC" -o "${HELLOC%.c}" ) && NOSTACKPROT_FLAGS="${NOSTACKPROT_FLAGS+$NOSTACKPROT_FLAGS }-fnostack-protector"
+export CFLAGS="-ffunction-sections -fdata-sections${NOPIC_FLAGS:+ $NOPIC_FLAGS}" # -fnostack-protector
 # proceed ...
 echo -e "Configuring and building ${cW}zlib${cZ}"
 (
@@ -156,7 +174,7 @@ echo -e "Configuring and building ${cW}zlib${cZ}"
 		make --no-print-directory -C "$BUILDDIR/zlib" install
 ) || { echo -e "${cR}ERROR:${cZ} zlib failed to build."; exit 1; }
 ((VERBOSE)) && echo -e "${cB}[DBG:$PRJNAME]${cZ} Cleaning extraneous files from Git clone."
-( cd "$PRJSRCDIR" && git clean -d -f ) || { echo -e "${cR}ERROR:${cZ} failed to 'git clean' $PRJNAME."; exit 1; }
+( cd "$PRJSRCDIR" && git clean -dfx ) || { echo -e "${cR}ERROR:${cZ} failed to 'git clean' $PRJNAME."; exit 1; }
 ( cd "$PRJSRCDIR" && git reset --hard ) || { echo -e "${cR}ERROR:${cZ} failed to 'git reset --hard' $PRJNAME."; exit 1; }
 echo -e "Configuring and building ${cW}$PRJ${cZ}"
 (
@@ -169,6 +187,7 @@ echo -e "Configuring and building ${cW}$PRJ${cZ}"
 			echo '#endif' >> "$BUILDDIR/linux/pkt_sched.h" && \
 		$DBGCONFIGURE $PRJSRCDIR/configure \
 			"--with-zlib=$BUILDDIR/zlib/tempinstall" \
+			--enable-static \
 			--disable-syslog \
 			--disable-lastlog \
 			--without-pam \
@@ -183,12 +202,13 @@ echo -e "Configuring and building ${cW}$PRJ${cZ}"
 			SCPPROGRESS=1 \
 			all strip \
 			&& \
-		TARFILE="$CURRABSPATH/dropbear-v${DROPBEAR_RELEASE##*_}-static.tgz" && \
-		trap 'rm -f "$LOCKFILE" "$TARFILE"; echo -e "'"${cW}INFO:${cZ}"' Removing the build directories due to signal."; rm -rf "'$BUILDDIR'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
+		TARFILE="$CURRABSPATH/dropbear-v${DROPBEAR_RELEASE##*_}-${CROSS_COMPILE}static.tgz" && \
+		{ ((DBG)) || { trap 'rm -f "$LOCKFILE" "$TARFILE"; echo -e "'"${cW}INFO:${cZ}"' Removing the build directories due to signal."; rm -rf "'$BUILDDIR'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT; } }
 		tar -czvf "$TARFILE" $(find -maxdepth 1 -type l) dropbearmulti && \
-		trap 'rm -f "$LOCKFILE"; echo -e "'"${cW}INFO:${cZ}"' Removing the build directories due to signal."; rm -rf "'$BUILDDIR'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
+		{ ((DBG)) || { trap 'rm -f "$LOCKFILE"; echo -e "'"${cW}INFO:${cZ}"' Removing the build directories due to signal."; rm -rf "'$BUILDDIR'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT; } }
 ) || { echo -e "${cR}ERROR:${cZ} $PRJ failed to build."; exit 1; }
 # Cleanup took place by the traps in the subshell already by this time, so simply remove the traps in the parent shell
+((DBG)) && rm -f "$LOCKFILE"
 trap - INT TERM EXIT
 let TIME_END=$(date +%s)
 show_time_diff $TIME_START $TIME_END      "Overall runtime:     %s (m:ss) with $PM parallel job(s)"
diff --git a/build-scripts/build-musl b/build-scripts/build-musl
--- a/build-scripts/build-musl
+++ b/build-scripts/build-musl
@@ -5,6 +5,11 @@ ORIG_CC="$CC_TO_USE"
 for tool in rm rmdir dirname readlink file tempfile grep tee git date make "${CC_TO_USE}" gpg tar wc; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 ( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBGCONFIGURE="$SHELL -x "; set -x; }
+CROSS_COMPILE_PATH=${CROSS_COMPILE%/*}
+CROSS_COMPILE=${CROSS_COMPILE##*/}
+if [[ -n "$CROSS_COMPILE_PATH" ]]; then
+	export PATH="$CROSS_COMPILE_PATH:$PATH"
+fi
 LOCKFILE="${TMPDIR=/tmp}/${CURRABSPATH//\//_}${0##*/}.lock"
 MEANDMYSELF=${0##*/}
 MUSLLIBC_VERSION="1.1.24"
@@ -127,7 +132,7 @@ BUILDDIR="${PRJSRCDIR}.build"
 prepare_src "$PRJNAME:git clone --progress --verbose $MUSLLIBC_GITREPO" "$MUSLLIBC_RELEASE"
 
 BUILD_MACH=$("${CC_TO_USE}" -dumpmachine 2> /dev/null)
-DEF_ARCH=$("${CC_TO_USE}" -print-multiarch 2> /dev/null)
+DEF_ARCH=$("${CC_TO_USE}" -print-multiarch 2> /dev/null || echo "$BUILD_MACH")
 M32_ARCH=$("${CC_TO_USE}" -m32 -print-multiarch 2> /dev/null)
 M64_ARCH=$("${CC_TO_USE}" -m64 -print-multiarch 2> /dev/null)
 [[ -n "$TARGETARCH" ]] || TARGETARCH="$DEF_ARCH"
@@ -135,7 +140,7 @@ TGTTRIPLET=$TARGETARCH
 TARGETDUPL=${TARGETARCH#*-}
 TARGETARCH=${TARGETARCH%%-*}
 CC_VERSION=$("${CC_TO_USE}" -dumpversion)
-((CC_VERSION >= 4)) || { echo -e "${cR}ERROR:${cZ} The compiler version is less than 4 (actual value: $CC_VERSION) and thus unsupported."; exit 1; }
+((${CC_VERSION%%.*} >= 4)) || { echo -e "${cR}ERROR:${cZ} The compiler version is less than 4 (actual value: $CC_VERSION) and thus unsupported."; exit 1; }
 if [[ -z "$TARGETGIVEN" ]] && [[ "$TARGETARCH" == "x86_64" ]] && [[ "$DEF_ARCH" == "$M64_ARCH" ]]; then
 	if "${CC_TO_USE}" -print-multi-lib 2> /dev/null|grep -q '^32;'; then
 		echo -e "${cW}INFO:${cZ} Building 32-bit ${cW}and${cZ} 64-bit Intel/AMD musl-libc (IA-32)"
