Updated Rust CLI build script

diff --git a/build-scripts/build-rust-cli-tools b/build-scripts/build-rust-cli-tools
--- a/build-scripts/build-rust-cli-tools
+++ b/build-scripts/build-rust-cli-tools
@@ -1,10 +1,12 @@
 #!/usr/bin/env bash
 # Possible sources for interesting Rust-based stuff: https://lib.rs + crates.io + cli.rs
 TARGET=${TARGET:-x86_64-unknown-linux-musl}
-OPENSSL_REFNAME=${OPENSSL_REFNAME:-OpenSSL_1_1_1j}
+OPENSSL_REFNAME=${OPENSSL_REFNAME:-OpenSSL_1_1_1k}
 OPENSSL_ARCH=${OPENSSL_ARCH:-x86}
+ZLIBURL="http://zlib.net/zlib-1.2.11.tar.gz"
+ZLIBSHA256="c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1"
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-for tool in chmod cp date dirname mkdir readlink sed tee grep ldd rustup sha256sum sort strip tar xz cargo; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in chmod cp curl date dirname mkdir readlink sed tee grep ldd rustup sha256sum sort strip tar wget xz cargo; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 test -d "$CURRABSPATH/cache" || mkdir -p "$CURRABSPATH/cache"
 TEMPDIR=${TEMPDIR:-"$(mktemp -dp "$CURRABSPATH/cache")"}
@@ -31,7 +33,6 @@ desed:SoptikHa2/desed
 diffr:mookid/diffr
 dirstat-rs:dirstat:scullionw/dirstat-rs
 diskonaut:imsnif/diskonaut
-dtool:guoxbin/dtool
 du-dust:dust:bootandy/dust
 dupe-krill:kornelski/dupe-krill
 dutree:nachoparker/dutree
@@ -102,7 +103,7 @@ verco:matheuslessarodrigues/verco
 viu:atanunq/viu
 vivid:sharkdp/vivid
 vopono:jamesmcm/vopono
-watchexec:watchexec/watchexec
+watchexec-cli:watchexec:watchexec/watchexec
 websocat:vi/websocat
 wool:grapegrip/wool
 xsv:BurntSushi/xsv
@@ -111,6 +112,9 @@ zenith:bvaisvil/zenith
 zoxide://lib.rs/crates/zoxide
 zrs:fauxfaux/zrs
 "
+# Candidates or temporarily removed:
+# * dtool:guoxbin/dtool
+#   -> failed to select a version for the requirement `zeroize = "^0.9.3"`
 
 # Number of jobs
 let PM=$(grep -c processor /proc/cpuinfo || echo 2)
@@ -186,16 +190,18 @@ function cargo_install
 	local TARGET="$4"
 	local TGTDIR="$5"
 	local OPENSSL_DIR="$TEMPDIR/openssl-dir"
+	local INCPATHS="$TEMPDIR/zlib/tempinstall/include${CPATH:+":$CPATH"}"
+	local LIBPATHS="$TEMPDIR/zlib/tempinstall/lib${LIBRARY_PATH:+":$LIBRARY_PATH"}"
 	#type ccache > /dev/null 2>&1 && CC="ccache musl-gcc" || CC="musl-gcc"
 	echo -e "${cW}INFO:${cZ} building ${cW}$BINNAME${cZ} ($HTTPS_URL)"
 	CC="musl-gcc"
 	# Binaries go into subfolder named ./bin underneath --root
 	if [[ "${CRATENAME:0:1}" == "@" ]]; then
-		( set -x; env OPENSSL_STATIC=1 OPENSSL_DIR="$OPENSSL_DIR" CC="$CC" cargo install --target "$TARGET" --target-dir "$TGTDIR/crates/$CRATENAME" --root "$TGTDIR" --git "$HTTPS_URL" --branch "${CRATENAME:1:${#CRATENAME}}" ) && return 0 || return 1
+		( set -x; env CPATH="$INCPATHS" LIBRARY_PATH="$LIBPATHS" OPENSSL_STATIC=1 OPENSSL_DIR="$OPENSSL_DIR" CC="$CC" cargo install --target "$TARGET" --target-dir "$TGTDIR/crates/$CRATENAME" --root "$TGTDIR" --git "$HTTPS_URL" --branch "${CRATENAME:1:${#CRATENAME}}" ) && return 0 || return 1
 	elif [[ "${CRATENAME:0:1}" == "~" ]]; then
-		( set -x; env OPENSSL_STATIC=1 OPENSSL_DIR="$OPENSSL_DIR" CC="$CC" cargo install --target "$TARGET" --target-dir "$TGTDIR/crates/$CRATENAME" --root "$TGTDIR" --git "$HTTPS_URL" --tag "${CRATENAME:1:${#CRATENAME}}" ) && return 0 || return 1
+		( set -x; env CPATH="$INCPATHS" LIBRARY_PATH="$LIBPATHS" OPENSSL_STATIC=1 OPENSSL_DIR="$OPENSSL_DIR" CC="$CC" cargo install --target "$TARGET" --target-dir "$TGTDIR/crates/$CRATENAME" --root "$TGTDIR" --git "$HTTPS_URL" --tag "${CRATENAME:1:${#CRATENAME}}" ) && return 0 || return 1
 	else
-		( set -x; env OPENSSL_STATIC=1 OPENSSL_DIR="$OPENSSL_DIR" CC="$CC" cargo install --target "$TARGET" "$CRATENAME" --target-dir "$TGTDIR/crates/$CRATENAME" --root "$TGTDIR" ) && return 0 || return 1
+		( set -x; env CPATH="$INCPATHS" LIBRARY_PATH="$LIBPATHS" OPENSSL_STATIC=1 OPENSSL_DIR="$OPENSSL_DIR" CC="$CC" cargo install --target "$TARGET" "$CRATENAME" --target-dir "$TGTDIR/crates/$CRATENAME" --root "$TGTDIR" ) && return 0 || return 1
 	fi
 	if [[ -x "$TGTDIR/bin/$BINNAME" ]]; then
 		if ! ldd "$TGTDIR/bin/$BINNAME"|grep -q 'statically linked'; then
@@ -280,6 +286,30 @@ function strip_and_store_binaries
 # Ensure we clean up after ourselves in any case
 let TIME_START=$(date +%s)
 trap 'echo "Removing temporary directory"; ( set -x; rm -rf "'$TEMPDIR'" ); trap - INT TERM EXIT; exit $?' INT TERM EXIT
+SRCTARBALLDIR="${TEMPDIR%/*}/source-tarballs"
+ZLIBPKG="$SRCTARBALLDIR/${ZLIBURL##*/}"
+echo -e "${cW}INFO:${cZ} fetching zlib source"
+[[ -d "$SRCTARBALLDIR" ]] || mkdir -p "$SRCTARBALLDIR"
+if [[ -f "$ZLIBPKG" ]]; then
+	echo -e "${cW}${ZLIBURL##*/} already downloaded, using cached copy${cZ}"
+else
+	wget -nc -O "$ZLIBPKG" "$ZLIBURL" || curl -o "$ZLIBPKG" "$ZLIBURL" || { echo -e "${cR}ERROR:${cZ} failed to download $ZLIBURL"; exit 1; }
+fi
+echo "$ZLIBSHA256  $ZLIBPKG"|sha256sum -c ||  { echo -e "${cR}ERROR:${cZ} SHA-2 (256-bit) hash does not match!"; exit 1; }
+( rm -rf "$TEMPDIR/zlib"; mkdir -p "$TEMPDIR/zlib" )
+if echo -ne "${cW}INFO:${cZ} unpacking zlib" && tar --strip-components=1 -C "$TEMPDIR/zlib" -xf "$ZLIBPKG" && mkdir -p "$TEMPDIR/zlib/tempinstall"; then
+	echo -e " ${cG}[OK]${cZ}"
+else
+	echo -e " ${cR}[failed]${cZ}"
+	exit 1
+fi
+echo -e "Configuring and building ${cW}zlib${cZ}"
+(
+	cd "$TEMPDIR/zlib" && \
+		( set -x; $DBGCONFIGURE./configure --static "--prefix=$TEMPDIR/zlib/tempinstall" ) && \
+		make --no-print-directory -C "$TEMPDIR/zlib" -j $PM && \
+		make --no-print-directory -C "$TEMPDIR/zlib" install
+) || { echo -e "${cR}ERROR:${cZ} zlib failed to build."; exit 1; }
 if [[ -z "$NOSSL" ]]; then
 	echo -e "${cW}INFO:${cZ} building OpenSSL"
 	openssl_build || exit 1
