Separating source dir and build dir

diff --git a/build-scripts/build-musl b/build-scripts/build-musl
--- a/build-scripts/build-musl
+++ b/build-scripts/build-musl
@@ -1,16 +1,17 @@
 #!/usr/bin/env bash
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
+for tool in dirname readlink file tempfile grep tee git date make gcc; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 ( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBGCONFIGURE="$SHELL -x "; set -x; }
 MEANDMYSELF=${0##*/}
 MUSLLIBC_RELEASE="v1.1.15"
 INSTALL_TO=${INSTALL_TO:-$HOME/bin/musl}
-BASEDIR="${BASEDIR:-$(pwd)}"
+BASEDIR="$CURRABSPATH"
 CACHEDIR="$BASEDIR/cache"
-for tool in file tempfile grep tee git date make gcc; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 
 function show_help
 {
-	echo -e "Syntax: $MEANDMYSELF [-h|-?] [-i <install-dir>] [-t <target-arch>] [-v] [-V <musl-libc-tag>]"
+	echo -e "Syntax: $MEANDMYSELF [-h|-?] [-i <install-dir>] [-t <target-triplet>] [-v] [-V <musl-libc-tag>]"
 	echo -e "\t${cW}-h | -?${cZ}"
 	echo -e "\t  Show this help"
 	echo -e "\t${cW}-i${cZ} <install-dir>"
@@ -19,8 +20,8 @@ function show_help
 	echo -e "\t  Be verbose about the actions (lines get leading '${cB}[DBG]${cZ}' string)."
 	echo -e "\t${cW}-V${cZ} <musl-libc-tag> ${cY}(if not given defaults to: $MUSLLIBC_RELEASE)${cZ}"
 	echo -e "\t  Tag to build instead of hardcoded default."
-	echo -e "\t${cW}-t${cZ} <target-arch>"
-	echo -e "\t  Target architecture, e.g. ${cW}x86_64-linux-gnu${cZ} or ${cW}i386-linux-gnu${cZ} or a"
+	echo -e "\t${cW}-t${cZ} <target-triplet>"
+	echo -e "\t  Target triplet, e.g. ${cW}x86_64-linux-gnu${cZ} or ${cW}i386-linux-gnu${cZ} or a"
 	echo -e "\t  comma-separated list of architectures."
 	echo -e "\t  ${cW}NOTE:${cZ} this can be useful on x86_64 to force only to build x86_64 or x86_32 instead of"
 	echo -e "\t  both."
@@ -107,8 +108,10 @@ echo -e "Working directory: $BASEDIR"
 let PM=$(grep -c processor /proc/cpuinfo)
 ((VERBOSE)) && echo -e "${cB}[DBG]${cZ} Number of parallel jobs, based on processor count: $PM."
 let TIME_START=$(date +%s)
-((VERBOSE)) && echo -e "${cB}[DBG]${cZ} Preparing core projects."
 PRJNAME="musl-libc"
+PRJSRCDIR="$CACHEDIR/$PRJNAME"
+BUILDDIR="${PRJSRCDIR}.build"
+((VERBOSE)) && echo -e "${cB}[DBG]${cZ} Preparing $PRJNAME"
 prepare_src "$PRJNAME:git clone http://git.musl-libc.org/cgit/musl/" "$MUSLLIBC_RELEASE"
 
 [[ -n "$TARGETARCH" ]] || TARGETARCH=$(gcc -dumpmachine)
@@ -137,20 +140,22 @@ fi
 for tgt in ${TARGETARCH//,/ }; do
 	echo -e "Now building for target ${cW}$tgt${cZ}"
 	((VERBOSE)) && echo -e "${cB}[DBG:$PRJNAME]${cZ} Cleaning extraneous files from Git clone."
-	( cd "$CACHEDIR/$PRJNAME" && git clean -d -f ) || { echo -e "${cR}ERROR:${cZ} failed to 'git clean' $PRJNAME."; exit 1; }
+	( cd "$PRJSRCDIR" && git clean -d -f ) || { echo -e "${cR}ERROR:${cZ} failed to 'git clean' $PRJNAME."; exit 1; }
 	case "$tgt" in
 	i?86|x86_32) # 32-bit Intel/AMD
 		ARCHARG="-m32"
 		( \
 			PREFIX="$INSTALL_TO" ; \
 			BITNESS="32" ; \
+			BLDDIR="$BUILDDIR$BITNESS" ; \
 			{ ((SPECIALSPEC)) && { DIRS="--bindir=$PREFIX/bin$BITNESS --libdir=$PREFIX/lib$BITNESS --includedir=$PREFIX/include$BITNESS"; rm -rf "$PREFIX/"{bin,lib,include}$BITNESS; true ; } || { rm -rf "$PREFIX/"{bin,lib,include}; true; } ; } ; \
-			cd "$CACHEDIR/$PRJNAME" && \
-			make distclean && \
-			( set -x; env CROSS_COMPILE="$CROSS_COMPILE" CFLAGS="-m$BITNESS -Wl,-melf_i386" ${DBGCONFIGURE}./configure --prefix="$PREFIX" $(echo "$DIRS ")--disable-shared --target="${tgt}-${TARGETDUPL}" ) && \
-			cp config.mak "../${tgt}-config.mak" && \
-			make -j $PM && \
-			make install \
+			cd "$PRJSRCDIR" && \
+			make --no-print-directory distclean && \
+			mkdir -p "$BLDDIR" && \
+			( cd "$BLDDIR"; set -x; env CROSS_COMPILE="$CROSS_COMPILE" CFLAGS="-m$BITNESS -Wl,-melf_i386" ${DBGCONFIGURE}$PRJSRCDIR/configure --srcdir="$PRJSRCDIR" --prefix="$PREFIX" $(echo "$DIRS ")--disable-shared --target="${tgt}-${TARGETDUPL}" ) && \
+			cp "$BLDDIR/config.mak" "../${tgt}-config.mak" && \
+			make --no-print-directory -C "$BLDDIR" -j$PM && \
+			make --no-print-directory -C "$BLDDIR" install \
 			)
 		;;
 	x86_64) # 64-bit Intel/AMD
@@ -158,23 +163,27 @@ for tgt in ${TARGETARCH//,/ }; do
 		( \
 			PREFIX="$INSTALL_TO" ; \
 			BITNESS="64" ; \
+			BLDDIR="$BUILDDIR$BITNESS" ; \
 			{ ((SPECIALSPEC)) && { DIRS="--bindir=$PREFIX/bin$BITNESS --libdir=$PREFIX/lib$BITNESS --includedir=$PREFIX/include$BITNESS"; rm -rf "$PREFIX/"{bin,lib,include}$BITNESS; true ; } || { rm -rf "$PREFIX/"{bin,lib,include}; true; } ; } ; \
-			cd "$CACHEDIR/$PRJNAME" && \
+			cd "$PRJSRCDIR" && \
 			make distclean && \
-			( set -x; env CROSS_COMPILE="$CROSS_COMPILE" CFLAGS="-m$BITNESS -Wl,-melf_x86_64" ${DBGCONFIGURE}./configure --prefix="$PREFIX" $(echo "$DIRS ")--disable-shared --target="${tgt}-${TARGETDUPL}" ) && \
-			cp config.mak "../${tgt}-config.mak" && \
-			make -j $PM && \
-			make install \
+			mkdir -p "$BLDDIR" && \
+			( cd "$BLDDIR"; set -x; env CROSS_COMPILE="$CROSS_COMPILE" CFLAGS="-m$BITNESS -Wl,-melf_x86_64" ${DBGCONFIGURE}$PRJSRCDIR/configure --srcdir="$PRJSRCDIR" --prefix="$PREFIX" $(echo "$DIRS ")--disable-shared --target="${tgt}-${TARGETDUPL}" ) && \
+			cp "$BLDDIR/config.mak" "../${tgt}-config.mak" && \
+			make --no-print-directory -C "$BLDDIR" -j$PM && \
+			make --no-print-directory -C "$BLDDIR" install \
 			)
 		;;
 	*) # native
 		( \
-			cd "$CACHEDIR/$PRJNAME" && \
-			make distclean && \
-			(set -x; ${DBGCONFIGURE}./configure --prefix="$INSTALL_TO" --disable-shared ) && \
-			cp config.mak "../${tgt}-config.mak" && \
-			make -j $PM && \
-			make install \
+			BLDDIR="$BUILDDIR$BITNESS" ; \
+			cd "$PRJSRCDIR" && \
+			make --no-print-directory distclean && \
+			mkdir -p "$BLDDIR" && \
+			(cd "$BLDDIR"; set -x; ${DBGCONFIGURE}$PRJSRCDIR/configure --srcdir="$PRJSRCDIR" --prefix="$INSTALL_TO" --disable-shared ) && \
+			cp "$BLDDIR/config.mak" "../${tgt}-config.mak" && \
+			make --no-print-directory -C "$BLDDIR" -j$PM && \
+			make --no-print-directory -C "$BLDDIR" install \
 			)
 		;;
 	esac
@@ -282,3 +291,4 @@ if [[ -n "$OLD_INSTALL_TO" ]]; then
 fi
 let TIME_END=$(date +%s)
 show_time_diff $TIME_START $TIME_END      "Overall runtime:     %s (m:ss) with $PM parallel job(s)"
+exit 0
