Consolidated some bits

diff --git a/build-scripts/build-cmake b/build-scripts/build-cmake
--- a/build-scripts/build-cmake
+++ b/build-scripts/build-cmake
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+# vim: set autoindent smartindent ts=4 sw=4 sts=4 noet filetype=sh:
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
 TOOLS_NEEDED="touch cat dirname readlink rm rmdir file tempfile grep tee git date make gcc"
 for tool in $TOOLS_NEEDED; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
@@ -131,7 +132,7 @@ function freeze_repo
 	local HASHPROG="$3"
 	shift 3
 	echo -e "${cW}freeze_repo(${cY}'$BASEDIR', '$TARGETDIR', '$HASHPROG', ${cG}" "$@" "${cW})${cZ}"
-	local TIMESTAMP=$(date +%Y-%m-%dT%H-%M-%S)
+	local TIMESTAMP=${TIMESTAMP:-$(date +%Y-%m-%dT%H-%M-%S)}
 	local TARNAME="packaged-${TIMESTAMP}-${TAR_TAG}.tar"
 	local UNPACKER="unpack-$TIMESTAMP-${TAR_TAG}"
 	echo "Packaging the source into $TARNAME"
@@ -154,12 +155,20 @@ function freeze_repo
 		for fname in "$@"; do
 			if [[ -f "$BASEDIR/$fname" ]]; then
 				( \
-					cd "$BASEDIR";
+					cd "$BASEDIR"; \
 					pname="${CACHEDIR##*/}/${fname}"; \
 					test -d "${pname%/*}" || mkdir -p "${pname%/*}"; \
 					cp -a "$fname" "${pname%/*}"/ ; \
 					$HASHPROG "$pname" | tee -a ${HASHPROG^^}S; \
 					echo "$pname" | tee -a "./$MEANDMYSELF.extrafiles" \
+				)
+			elif [[ -f "$fname" ]]; then
+				( \
+					bname="${fname##*/}"; \
+					cd "$BASEDIR" && \
+					cp -na "$fname" .; \
+					$HASHPROG "$bname" | tee -a ${HASHPROG^^}S; \
+					echo "$bname" | tee -a "./$MEANDMYSELF.extrafiles" \
 				)
 			fi
 		done
@@ -170,14 +179,22 @@ function freeze_repo
 		fi
 		cat - >> "$TARGETDIR/$UNPACKER" <<-EOF
 			#!/usr/bin/env bash
-			TS="$TIMESTAMP"
+			TS="\${TS:-$TIMESTAMP}"
 			T="${TARNAME//$TIMESTAMP/\$TS}"
-			D="\$TS-${TAR_TAG}"
+			D="\${TGTDIR:-\$TS-${TAR_TAG}}"
 			R="./$MEANDMYSELF"
 			U="${UNPACKER//$TIMESTAMP/\$TS}"
 			echo "Unpacking \$T into ./\$D \$( [[ "x\$1" == "x-c" ]] && echo "and removing archive plus unpacker upon success" )"
-			mkdir "./\$D" && tar -C "./\$D" -xf "./\$T" && ( cd "./\$D"; $HASHPROG -c ${HASHPROG^^}S || exit \$?; [[ -x \$R ]] && \$R -r "\$TS" )
-			[[ "x\$1" == "x-c" ]] && { echo "Also removing \$U and \$T"; rm -f "./\$U" "./\$T"; }
+			test -d "./\$D" || mkdir -p "./\$D" || { echo -e "ERROR: failed to create target directory (\$D)"; exit 1; }
+			tar -C "./\$D" -xf "./\$T" || { echo -e "ERROR: failed to unpack tarball (\$T)"; exit 1; }
+			( cd "./\$D"; $HASHPROG -c ${HASHPROG^^}S || exit \$?; ) || { echo -e "ERROR: failed to validate hashes in target directory (\$D)"; exit 1; }
+			if [[ -x "./\$D/\$R" ]]; then
+				( set -x; cd "\$D"; \$R -r "\$TS" ) || { echo -e "ERROR: failed to revive build package (\$D)"; exit 1; }
+			fi
+			if [[ "x\$1" == "x-c" ]]; then
+				echo "Also removing \$U and \$T"
+				rm -f "./\$U" "./\$T"
+			fi
 		EOF
 		chmod +x "$TARGETDIR/$UNPACKER"
 		rm -f "$BASEDIR"/*-$TIMESTAMP.gitbundle{,.${HASHPROG^^}} "$BASEDIR"/${HASHPROG^^}S "$BASEDIR/$MEANDMYSELF.extrafiles"
diff --git a/build-scripts/build-dropbear b/build-scripts/build-dropbear
--- a/build-scripts/build-dropbear
+++ b/build-scripts/build-dropbear
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+# vim: set autoindent smartindent ts=4 sw=4 sts=4 noet filetype=sh:
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
 CC_TO_USE=${CROSS_COMPILE}${CC:-gcc}
 ORIG_CC="$CC_TO_USE"
@@ -24,6 +25,7 @@ INSTALL_TO=${INSTALL_TO:-$HOME/bin/$TAR_TAG}
 BASEDIR="${BASEDIR:-$(pwd)}"
 CACHEDIR="${CACHEDIR:-$BASEDIR/cache}"
 CMDLINE_OPTIONS="h?cCgGi:pr:vV:"
+BUILDMUSL="$CURRABSPATH/build-musl"
 
 function show_help
 {
@@ -54,6 +56,16 @@ function show_help
 	echo -e "\t${cW}-V${cZ} <release-tag> ${cY}(if not given defaults to: $RELEASE_TAG)${cZ}"
 	echo -e "\t  Tag to build instead of hardcoded default."
 	echo ""
+	echo ""
+	echo -e "By setting environment variable ${cW}CROSS_COMPILE${cZ} you can point this"
+	echo -e "script to an alternative toolchain. Please use it with an absolute path."
+	echo ""
+	echo -e "Suppose you have ${cW}arm-none-linux-gnueabi-${cY}gcc${cZ} inside /opt/arm/bin"
+	echo -e "you should invoke this script approximately as follows:"
+	echo ""
+	echo -e "  env ${cW}CROSS_COMPILE${cZ}=${cG}/opt/arm/bin/${cW}arm-none-linux-gnueabi-${cZ} $MEANDMYSELF ..."
+	echo ""
+
 }
 
 function prepare_src
@@ -141,7 +153,7 @@ function freeze_repo
 	local HASHPROG="$3"
 	shift 3
 	echo -e "${cW}freeze_repo(${cY}'$BASEDIR', '$TARGETDIR', '$HASHPROG', ${cG}" "$@" "${cW})${cZ}"
-	local TIMESTAMP=$(date +%Y-%m-%dT%H-%M-%S)
+	local TIMESTAMP=${TIMESTAMP:-$(date +%Y-%m-%dT%H-%M-%S)}
 	local TARNAME="packaged-${TIMESTAMP}-${TAR_TAG}.tar"
 	local UNPACKER="unpack-$TIMESTAMP-${TAR_TAG}"
 	echo "Packaging the source into $TARNAME"
@@ -164,12 +176,20 @@ function freeze_repo
 		for fname in "$@"; do
 			if [[ -f "$BASEDIR/$fname" ]]; then
 				( \
-					cd "$BASEDIR";
+					cd "$BASEDIR"; \
 					pname="${CACHEDIR##*/}/${fname}"; \
 					test -d "${pname%/*}" || mkdir -p "${pname%/*}"; \
 					cp -a "$fname" "${pname%/*}"/ ; \
 					$HASHPROG "$pname" | tee -a ${HASHPROG^^}S; \
 					echo "$pname" | tee -a "./$MEANDMYSELF.extrafiles" \
+				)
+			elif [[ -f "$fname" ]]; then
+				( \
+					bname="${fname##*/}"; \
+					cd "$BASEDIR" && \
+					cp -na "$fname" .; \
+					$HASHPROG "$bname" | tee -a ${HASHPROG^^}S; \
+					echo "$bname" | tee -a "./$MEANDMYSELF.extrafiles" \
 				)
 			fi
 		done
@@ -180,14 +200,22 @@ function freeze_repo
 		fi
 		cat - >> "$TARGETDIR/$UNPACKER" <<-EOF
 			#!/usr/bin/env bash
-			TS="$TIMESTAMP"
+			TS="\${TS:-$TIMESTAMP}"
 			T="${TARNAME//$TIMESTAMP/\$TS}"
-			D="\$TS-${TAR_TAG}"
+			D="\${TGTDIR:-\$TS-${TAR_TAG}}"
 			R="./$MEANDMYSELF"
 			U="${UNPACKER//$TIMESTAMP/\$TS}"
 			echo "Unpacking \$T into ./\$D \$( [[ "x\$1" == "x-c" ]] && echo "and removing archive plus unpacker upon success" )"
-			mkdir "./\$D" && tar -C "./\$D" -xf "./\$T" && ( cd "./\$D"; $HASHPROG -c ${HASHPROG^^}S || exit \$?; [[ -x \$R ]] && \$R -r "\$TS" )
-			[[ "x\$1" == "x-c" ]] && { echo "Also removing \$U and \$T"; rm -f "./\$U" "./\$T"; }
+			test -d "./\$D" || mkdir -p "./\$D" || { echo -e "ERROR: failed to create target directory (\$D)"; exit 1; }
+			tar -C "./\$D" -xf "./\$T" || { echo -e "ERROR: failed to unpack tarball (\$T)"; exit 1; }
+			( cd "./\$D"; $HASHPROG -c ${HASHPROG^^}S || exit \$?; ) || { echo -e "ERROR: failed to validate hashes in target directory (\$D)"; exit 1; }
+			if [[ -x "./\$D/\$R" ]]; then
+				( set -x; cd "\$D"; \$R -r "\$TS" ) || { echo -e "ERROR: failed to revive build package (\$D)"; exit 1; }
+			fi
+			if [[ "x\$1" == "x-c" ]]; then
+				echo "Also removing \$U and \$T"
+				rm -f "./\$U" "./\$T"
+			fi
 		EOF
 		chmod +x "$TARGETDIR/$UNPACKER"
 		rm -f "$BASEDIR"/*-$TIMESTAMP.gitbundle{,.${HASHPROG^^}} "$BASEDIR"/${HASHPROG^^}S "$BASEDIR/$MEANDMYSELF.extrafiles"
@@ -222,7 +250,7 @@ while getopts "$CMDLINE_OPTIONS" opt; do
 	p)  ((NOCHECKOUT)) && { echo -e "${cR}ERROR:${cZ} ${cY}-C${cZ} and ${cY}-p${cZ}/${cY}-c${cZ} are mutually exclusive."; exit 1; }
 		ONLYCHECKOUT=1
 		BUNDLEGIT=1
-		assert_tools "$opt" cp sha256sum tar tee xz
+		assert_tools "$opt" cp sha256sum tar tee xz "$BUILDMUSL"
 		echo "Doing only a checkout and then packaging bundled clones into a .tar file."
 		;;
 	r)  [[ -n "$OPTARG" ]] || { echo -e "${cR}ERROR:${cZ} ${cY}-$opt${cZ} requires an argument." >&2; exit 1; }
@@ -247,6 +275,9 @@ if ! (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
 	echo -e "${cR}ERROR:${cZ} Lock failed, PID $(cat "$LOCKFILE") [$LOCKFILE]" >&2
 	exit 1
 fi
+if [[ "$CC_TO_USE" != "$ORIG_CC" ]]; then
+	echo -e "${cW}INFO:${cZ} cross-compilation was requested: CROSS_COMPILE=$CROSS_COMPILE"
+fi
 trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
 echo -e "\tWorking directory: $BASEDIR"
 let PM=$(grep -c processor /proc/cpuinfo || echo 2)
@@ -257,6 +288,11 @@ BUILDDIR="${PRJSRCDIR}.build"
 for i in "$PRJNAME:git clone $GITREPO"; do
 	prepare_src "$i" "$RELEASE_TAG" "$CACHEDIR"
 done
+if ((REVIVEPKG)); then
+	if [[ -x "$CURRABSPATH/unpack-$REVIVETS-musl" ]]; then
+		( set -x; cd "$CURRABSPATH"; env TGTDIR=. ./unpack-$REVIVETS-musl -c )
+	fi
+fi
 SRCTARBALLDIR="$CACHEDIR/source-tarballs"
 ZLIBPKG="$SRCTARBALLDIR/${ZLIBURL##*/}"
 [[ -d "$SRCTARBALLDIR" ]] || mkdir -p "$SRCTARBALLDIR"
@@ -274,12 +310,12 @@ if ((ONLYCHECKOUT==0)); then
 	if [[ -x "$MUSL_INSTALLDIR/$MUSLGCC" ]]; then
 		echo -e "${cW}INFO:${cZ} Skipping build of musl-libc (found cached copy at $MUSL_INSTALLDIR)."
 	else
-		BUILDMUSL="$CURRABSPATH/build-musl"
-		( echo -e "${cW}Building ${MUSLGCC##*/} now${cZ}"; cd "${BUILDMUSL%/*}" && ./${BUILDMUSL##*/} -i "$MUSL_INSTALLDIR" ) || { echo -e "${cR}ERROR:${cZ} failed to build musl-libc for ${ORIG_CC}."; exit 1; }
+		assert_tools "" "$BUILDMUSL"
+		( echo -e "${cW}Building ${MUSLGCC##*/} now${cZ}"; cd "${BUILDMUSL%/*}" && ${CROSS_COMPILE:+env CROSS_COMPILE="${CROSS_COMPILE_PATH:+"$CROSS_COMPILE_PATH/"}$CROSS_COMPILE"} ./${BUILDMUSL##*/} -i "$MUSL_INSTALLDIR" ) || { echo -e "${cR}ERROR:${cZ} failed to build musl-libc for ${ORIG_CC}."; exit 1; }
 	fi
 	export PATH="$MUSL_INSTALLDIR:$PATH"
 	((DBG)) || { trap 'rm -f "$LOCKFILE"; echo -e "'"${cW}INFO:${cZ}"' Removing the build directories due to signal."; rm -rf "'$BUILDDIR'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT; }
-	( rm -rf "$BUILDDIR"; mkdir -p "$BUILDDIR/zlib" )
+	( rm -rf "$BUILDDIR/zlib"; mkdir -p "$BUILDDIR/zlib" )
 	if echo -n "... unpacking zlib" && tar --strip-components=1 -C "$BUILDDIR/zlib" -xf "$ZLIBPKG" && mkdir -p "$BUILDDIR/zlib/tempinstall"; then
 		echo -e " ${cG}[OK]${cZ}"
 	else
@@ -296,8 +332,7 @@ if ((ONLYCHECKOUT==0)); then
 		}
 	EOF
 	# Configure GCC for our purpose
-	export CC="$MUSLGCC -static"
-	export LDFLAGS="-Wl,--gc-sections -Wl,--hash-style=both"
+	export CC="$ORIG_CC -static"
 	( set -x; $MUSLGCC -no-pie "$HELLOC" -o "${HELLOC%.c}" ) && NOPIC_FLAGS="${NOPIC_FLAGS+$NOPIC_FLAGS }-no-pie"
 	( set -x; $MUSLGCC -fno-pic "$HELLOC" -o "${HELLOC%.c}" ) && NOPIC_FLAGS="${NOPIC_FLAGS+$NOPIC_FLAGS }-fno-pic"
 	( set -x; $MUSLGCC -fno-PIC "$HELLOC" -o "${HELLOC%.c}" ) && NOPIC_FLAGS="${NOPIC_FLAGS+$NOPIC_FLAGS }-fno-PIC"
@@ -307,19 +342,28 @@ if ((ONLYCHECKOUT==0)); then
 	echo -e "Configuring and building ${cW}zlib${cZ}"
 	(
 		cd "$BUILDDIR/zlib" && \
-			$DBGCONFIGURE./configure --static "--prefix=$BUILDDIR/zlib/tempinstall" && \
+			( set -x; $DBGCONFIGURE./configure --static "--prefix=$BUILDDIR/zlib/tempinstall" ) && \
 			make --no-print-directory -C "$BUILDDIR/zlib" -j $PM && \
 			make --no-print-directory -C "$BUILDDIR/zlib" install
 	) || { echo -e "${cR}ERROR:${cZ} zlib failed to build."; exit 1; }
+	export LDFLAGS="-Wl,--gc-sections -Wl,--hash-style=both"
+	[[ -d "$MUSL_INSTALLDIR" ]] || { echo -e "${cR}ERROR:${cZ} $MUSL_INSTALLDIR not found!"; exit 1; }
+	[[ -x "$MUSL_INSTALLDIR/$MUSLGCC" ]] || { echo -e "${cR}ERROR:${cZ} $MUSL_INSTALLDIR/$MUSLGCC not found!"; exit 1; }
+	export CC="$MUSLGCC -static"
 	((VERBOSE)) && echo -e "${cB}[DBG:$PRJNAME]${cZ} Cleaning extraneous files from Git clone."
 	( cd "$PRJSRCDIR" && git clean -dfx ) || { echo -e "${cR}ERROR:${cZ} failed to 'git clean' $PRJNAME."; exit 1; }
 	( cd "$PRJSRCDIR" && git reset --hard ) || { echo -e "${cR}ERROR:${cZ} failed to 'git reset --hard' $PRJNAME."; exit 1; }
 	echo -e "Configuring and building ${cW}$PRJ${cZ}"
 	(
+		rm -rf "$BUILDDIR/linux"; \
+		TARFILE="$CURRABSPATH/dropbear-v${RELEASE_TAG##*_}-${CROSS_COMPILE:-"$(uname -m)-"}static.tgz"; \
+		if ((DBG)); then \
+			trap 'rm -f "$LOCKFILE" "$TARFILE"; echo -e "'"${cW}INFO:${cZ}"' Removing the build directories due to signal."; rm -rf "'$BUILDDIR'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT; \
+		fi; \
 		cd "$PRJSRCDIR" && \
 			autoconf && autoheader && \
 		cd "$BUILDDIR" && \
-			mkdir $BUILDDIR/linux && \
+			mkdir "$BUILDDIR/linux" && \
 			touch "$BUILDDIR/linux/types.h" && \
 			grep -E '(__LINUX_PKT_SCHED_H|#define TC_PRIO_)' /usr/include/linux/pkt_sched.h > $BUILDDIR/linux/pkt_sched.h && \
 				echo '#endif' >> "$BUILDDIR/linux/pkt_sched.h" && \
@@ -335,25 +379,30 @@ if ((ONLYCHECKOUT==0)); then
 				&& \
 			make --no-print-directory -C "$BUILDDIR" -j $PM \
 				PROGRAMS="dropbear dbclient scp dropbearkey dropbearconvert" \
-				MULTI=1 \
-				STATIC=1 \
-				SCPPROGRESS=1 \
+				MULTI=1 STATIC=1 SCPPROGRESS=1 \
+				${CROSS_COMPILE:+STRIP=${CROSS_COMPILE}strip AR=${CROSS_COMPILE}ar RANLIB=${CROSS_COMPILE}ranlib} \
 				all strip \
 				&& \
-			TARFILE="$CURRABSPATH/dropbear-v${RELEASE_TAG##*_}-${CROSS_COMPILE}static.tgz" && \
-			{ ((DBG)) || { trap 'rm -f "$LOCKFILE" "$TARFILE"; echo -e "'"${cW}INFO:${cZ}"' Removing the build directories due to signal."; rm -rf "'$BUILDDIR'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT; } }
-			tar -czvf "$TARFILE" $(find -maxdepth 1 -type l) dropbearmulti && \
-			{ ((DBG)) || { trap 'rm -f "$LOCKFILE"; echo -e "'"${cW}INFO:${cZ}"' Removing the build directories due to signal."; rm -rf "'$BUILDDIR'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT; } }
+			sha256sum dropbearmulti|tee dropbearmulti.SHA256SUM && \
+			if ! tar -czvf "$TARFILE" $(find -maxdepth 1 -type l) dropbearmulti{,.SHA256SUM}; then
+				exit 1; \
+			fi; \
+			if ((DBG)); then \
+				trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT; \
+			else \
+				trap 'rm -f "$LOCKFILE"; rm -rf "'$BUILDDIR'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT; \
+			fi
 	) || { echo -e "${cR}ERROR:${cZ} $PRJ failed to build."; exit 1; }
-	# Cleanup took place by the traps in the subshell already by this time, so simply remove the traps in the parent shell
-	((DBG)) && rm -f "$LOCKFILE"
 	trap - INT TERM EXIT
 fi
 if ((ONLYCHECKOUT==1)); then
 	show_time_diff $TIME_START $TIME_GIT      "Git operations took: %s"
 fi
 if ((BUNDLEGIT==1)); then
-	freeze_repo "$CACHEDIR" "$BASEDIR" sha256sum $PRJNAME ${ZLIBPKG#$CACHEDIR/}
+	export TIMESTAMP=$(date +%Y-%m-%dT%H-%M-%S)
+	trap 'rm -f "$LOCKFILE" "'${BUILDMUSL%/*}/unpack-$TIMESTAMP-musl'" "'${BUILDMUSL%/*}/packaged-$TIMESTAMP-musl.tar'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
+	( cd "${BUILDMUSL%/*}"; set -x; ./${BUILDMUSL##*/} -pG ) || { echo -e "${cR}ERROR:${cZ} failed to package build-musl and its dependencies."; exit 1; }
+	freeze_repo "$CACHEDIR" "$BASEDIR" sha256sum $PRJNAME ${ZLIBPKG#$CACHEDIR/} "${BUILDMUSL%/*}/unpack-$TIMESTAMP-musl" "${BUILDMUSL%/*}/packaged-$TIMESTAMP-musl.tar"
 	let TIME_GITBUNDLE=$(date +%s)
 	show_time_diff $TIME_GIT $TIME_GITBUNDLE                "Packaging took:      %s"
 fi
