Honing some more sharp edges

diff --git a/build-scripts/build-llvm-and-clang b/build-scripts/build-llvm-and-clang
--- a/build-scripts/build-llvm-and-clang
+++ b/build-scripts/build-llvm-and-clang
@@ -284,6 +284,9 @@ else
 	CC="gcc"
 	CXX="g++"
 fi
+if [[ "$MAKETOOL" == "ninja" ]]; then
+	MAKE_VERBOSE="${VERBOSE:+ --verbose}"
+fi
 let TIME_GIT=$(date +%s)
 if ((ONLYCHECKOUT==0)) && ((NOBUILD==0)); then
 	((VERBOSE)) && echo -e "${cB}[DBG]${cZ} Doing build for $TARGETS into $INSTALL_TO."
@@ -313,10 +316,10 @@ if ((ONLYCHECKOUT==0)) && ((NOBUILD==0)); then
 				"$BASEDIR/llvm/llvm" ) || { echo -e "${cR}ERROR:${cZ}  ${cW}cmake${cZ} failed."; exit 1; }
 			let TIME_CONFIGURE=$(date +%s)
 			# FIXME/TODO: add _options_ to enable optimizations and disable assertions somehow?! (i.e. don't hardcode them)
-			( set -x; env ENABLE_OPTIMIZED=1 DISABLE_ASSERTIONS=1 ${DBG:+TOOL_VERBOSE=1} "${MAKETOOL}" -j $PM )  || { echo -e "${cR}ERROR:${cZ}  ${cW}make${cZ} failed."; exit 1; }
+			( set -x; env ENABLE_OPTIMIZED=1 DISABLE_ASSERTIONS=1 ${DBG:+TOOL_VERBOSE=1} "${MAKETOOL}"${MAKE_VERBOSE} -j $PM )  || { echo -e "${cR}ERROR:${cZ}  ${cW}make${cZ} failed."; exit 1; }
 			let TIME_MAKE=$(date +%s)
 			if ((RUN_TESTS)); then
-				( set -x; "${MAKETOOL}" -j $PM test )  || { echo -e "${cR}ERROR:${cZ}  ${cW}$MAKETOOL test${cZ} failed."; exit 1; }
+				( set -x; "${MAKETOOL}"${MAKE_VERBOSE} -j $PM test )  || { echo -e "${cR}ERROR:${cZ}  ${cW}$MAKETOOL test${cZ} failed."; exit 1; }
 			fi
 			if ((NOINSTALL == 0)); then
 				if [[ -d "$INSTALL_TO" ]]; then
@@ -325,7 +328,7 @@ if ((ONLYCHECKOUT==0)) && ((NOBUILD==0)); then
 					mv "$INSTALL_TO" "${INSTALL_TO%/*}/$OLD_INSTALL_TO" || { echo -e "${cR}ERROR:${cZ} failed to move $INSTALL_TO out of the way."; exit 1; }
 					trap 'rm -f "$LOCKFILE"; echo -e "'"${cW}INFO:${cZ}"' Moving back your previous LLVM from '$OLD_INSTALL_TO' due to signal"; rm -rf "'$INSTALL_TO'"; mv "'${INSTALL_TO%/*}/$OLD_INSTALL_TO'" "'$INSTALL_TO'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
 				fi
-				( set -x; env ENABLE_OPTIMIZED=1 DISABLE_ASSERTIONS=1 ${DBG:+TOOL_VERBOSE=1} "${MAKETOOL}" -j $PM install )  || { echo -e "${cR}ERROR:${cZ}  ${cW}$MAKETOOL install${cZ} failed."; exit 1; }
+				( set -x; env ENABLE_OPTIMIZED=1 DISABLE_ASSERTIONS=1 ${DBG:+TOOL_VERBOSE=1} "${MAKETOOL}"${MAKE_VERBOSE} -j $PM install )  || { echo -e "${cR}ERROR:${cZ}  ${cW}$MAKETOOL install${cZ} failed."; exit 1; }
 				trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
 			fi
 			popd || { echo -e "${cR}ERROR:${cZ} could not ${cY}popd${cZ}."; exit 1; }
@@ -337,7 +340,7 @@ if ((ONLYCHECKOUT==0)) && ((NOBUILD==0)); then
 			pushd "$BASEDIR/3rdparty/binutils" || { echo -e "${cR}ERROR:${cZ} could not ${cW}pushd${cZ}."; exit 1; }
 			( set -x; ${USE_CLANG:+env CC=${CLANG:-clang} CXX=${CLANGPPLUS:-clang++}} ./configure --disable-werror --disable-gold --enable-ld --program-suffix=.clang --prefix=$INSTALL_TO ) || { echo -e "${cR}ERROR:${cZ} ${cY}./configure${cZ} failed."; exit 1; }
 			if ((NOINSTALL == 0)); then
-				( set -x; "${MAKETOOL}" -j $PM && "${MAKETOOL}" install ) || { echo -e "${cR}ERROR:${cZ} ${cW}make${cZ} or ${cW}$MAKETOOL install${cZ} failed."; exit 1; }
+				( set -x; "${MAKETOOL}"${MAKE_VERBOSE} -j $PM && "${MAKETOOL}"${MAKE_VERBOSE} install ) || { echo -e "${cR}ERROR:${cZ} ${cW}make${cZ} or ${cW}$MAKETOOL install${cZ} failed."; exit 1; }
 			fi
 			popd || { echo -e "${cR}ERROR:${cZ} could not ${cW}popd${cZ}."; exit 1; }
 		fi
