Fixup to allow building with cargo install --git

diff --git a/build-scripts/build-rust-cli-tools b/build-scripts/build-rust-cli-tools
--- a/build-scripts/build-rust-cli-tools
+++ b/build-scripts/build-rust-cli-tools
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
 # Possible sources for interesting Rust-based stuff: https://lib.rs + crates.io + cli.rs
 TARGET=${TARGET:-x86_64-unknown-linux-musl}
-TEMPDIR=${TEMPDIR:-"$(mktemp -dp "$(pwd)/cache")"}
 OPENSSL_REFNAME=${OPENSSL_REFNAME:-OpenSSL_1_1_1h}
 OPENSSL_ARCH=${OPENSSL_ARCH:-x86}
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-for tool in cp date dirname mkdir readlink tee grep ldd rustup sort strip tar xz cargo; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in cp date dirname mkdir readlink tee grep ldd rustup sha256sum sort strip tar xz cargo; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
+test -d "$CURRABSPATH/cache" || mkdir -p "$CURRABSPATH/cache"
+TEMPDIR=${TEMPDIR:-"$(mktemp -dp "$CURRABSPATH/cache")"}
 ( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBG=1; DEBUG=1; DBGCONFIGURE="$SHELL -x "; set -x; }
 if ! rustup target list --installed|grep -q "$TARGET"; then
 	echo -e "${cR}ERROR:${cZ} missing Rust target ${cW}${TARGET}${cZ}."
@@ -15,6 +16,7 @@ if ! rustup target list --installed|grep -q "$TARGET"; then
 fi
 # These can be installed using 'cargo install' and statically linked against musl libc
 SIMPLE_INSTALLS="\
+@main:nat:willdoescode/nat
 b3sum:BLAKE3-team/BLAKE3
 bandwhich:imsnif/bandwhich
 bat:sharkdp/bat
@@ -78,17 +80,29 @@ function git_checkout
 	local SUBDIR="$2"
 	local GITREF="$3"
 	local TEMPDIR="$4"
+	local REPOID="${REPOURL#http*://}"
+	REPOID="${REPOID%.git}"
+	REPOID="${REPOID//\//_}"
+	local GITBNDL="${SUBDIR//\//_}_$REPOID.gitbundle"
 	test -d "$TEMPDIR/$SUBDIR" && rm -rf "$TEMPDIR/$SUBDIR"
-	( cd "$TEMPDIR"; set -x; git clone "$REPOURL" "$SUBDIR" ) || { echo -e "${cR}ERROR:${cZ} failed to clone $REPOURL"; return 1; }
-	( cd "$TEMPDIR"; set -x; git -C "$SUBDIR" config branch.master.rebase true ) || { echo -e "${cR}ERROR:${cZ} could not set 'git config branch.master.rebase true' for $SUBDIR."; return 1; }
+	# Revive existing bundle
+	if [[ -e "$TEMPDIR/../$GITBNDL" ]]; then
+		( cd "$TEMPDIR/.."; set -x; sha256sum -c "$GITBNDL.SHA256SUM" ) || { echo -e "${cR}ERROR:${cZ} failed to verify $GITBNDL"; return 1; }
+		( cd "$TEMPDIR"; set -x; git clone "../$GITBNDL" "$SUBDIR" ) || { echo -e "${cR}ERROR:${cZ} failed to clone $GITBNDL"; return 1; }
+		( cd "$TEMPDIR"; set -x; git -C "$SUBDIR" remote set-url origin "$REPOURL" ) || { echo -e "${cR}ERROR:${cZ} failed setting URL of remote"; return 1; }
+	else # ... or clone from upstream URL
+		( cd "$TEMPDIR"; set -x; git clone --mirror "$REPOURL" "$SUBDIR/.git" ) || { echo -e "${cR}ERROR:${cZ} failed to clone $REPOURL"; return 1; }
+	fi
+	( cd "$TEMPDIR"; set -x; git -C "$SUBDIR" config --bool core.bare false ) || { echo -e "${cR}ERROR:${cZ} failed marking $SUBDIR non-bare"; return 1; }
+	( cd "$TEMPDIR"; set -x; git -C "$SUBDIR" config --bool branch.master.rebase true ) || { echo -e "${cR}ERROR:${cZ} could not set 'git config branch.master.rebase true' for $SUBDIR."; return 1; }
 	( cd "$TEMPDIR"; echo -en "branch.master.rebase = " && git -C "$SUBDIR" config --get branch.master.rebase )
+	( cd "$TEMPDIR"; set -x; git -C "$SUBDIR" checkout --detach -f $GITREF ) || { echo -e "${cR}ERROR:${cZ} failed to check out $GITREF for $SUBDIR."; return 1; }
 	( cd "$TEMPDIR"; set -x; git -C "$SUBDIR" clean -dfx) || { echo -e "${cR}ERROR:${cZ} failed to 'git clean -dfx' $SUBDIR."; return 1; }
-	( cd "$TEMPDIR"; set -x; git -C "$SUBDIR" fetch; git -C "$SUBDIR" fetch --tags ) || { echo -e "${cY}WARNING:${cZ} failed to 'git fetch' $SUBDIR."; }
+	( cd "$TEMPDIR"; set -x; git -C "$SUBDIR" fetch --all; git -C "$SUBDIR" fetch --tags ) || { echo -e "${cY}WARNING:${cZ} failed to 'git fetch' $SUBDIR."; }
 	( cd "$TEMPDIR"; set -x; git -C "$SUBDIR" remote prune origin ) || { echo -e "${cY}WARNING:${cZ} failed to 'git remote prune origin' $SUBDIR."; }
-	( cd "$TEMPDIR"; set -x; git -C "$SUBDIR" checkout -f $GITREF ) || { echo -e "${cR}ERROR:${cZ} failed to check out $GITREF for $SUBDIR."; return 1; }
-	if git -C "$TEMPDIR" --git-dir="$SUBDIR/.git" rev-parse --symbolic --branches|grep -q "$GITREF"; then
-		( cd "$TEMPDIR"; set -x; git -C "$SUBDIR" merge --ff-only origin/$GITREF ) || { echo -e "${cR}ERROR:${cZ} failed to fast-forward to origin/$GITREF for $SUBDIR."; exit 1; }
-	fi || return $?
+	# Bundle that stuff as a cached copy
+	( cd "$TEMPDIR"; set -x; git -C "$SUBDIR" bundle create "../../$GITBNDL" --all ) || { echo -e "${cR}ERROR:${cZ} failed to cache $SUBDIR in a Git bundle."; return 1; }
+	( cd "$TEMPDIR/.."; set -x; sha256sum "$GITBNDL"|tee "$GITBNDL.SHA256SUM" ) || { echo -e "${cR}ERROR:${cZ} failed to hash the $SUBDIR Git bundle."; return 1; }
 	return 0
 }
 
@@ -130,7 +144,11 @@ function cargo_install
 	local TGTDIR="$5"
 	local OPENSSL_DIR="$TEMPDIR/openssl-dir"
 	# Binaries go into subfolder named ./bin underneath --root
-	( set -x; env OPENSSL_STATIC=1 OPENSSL_DIR="$OPENSSL_DIR" CC=musl-gcc cargo install --target "$TARGET" "$CRATENAME" --target-dir "$TGTDIR/crates/$CRATENAME" --root "$TGTDIR" ) && return 0 || return 1
+	if [[ "${CRATENAME:0:1}" == "@" ]]; then
+		( set -x; env OPENSSL_STATIC=1 OPENSSL_DIR="$OPENSSL_DIR" CC=musl-gcc cargo install --target "$TARGET" --target-dir "$TGTDIR/crates/$CRATENAME" --root "$TGTDIR" --git "$HTTPS_URL" --branch "${CRATENAME:1:${#CRATENAME}}" ) && return 0 || return 1
+	else
+		( set -x; env OPENSSL_STATIC=1 OPENSSL_DIR="$OPENSSL_DIR" CC=musl-gcc cargo install --target "$TARGET" "$CRATENAME" --target-dir "$TGTDIR/crates/$CRATENAME" --root "$TGTDIR" ) && return 0 || return 1
+	fi
 	if [[ -x "$TGTDIR/bin/$BINNAME" ]]; then
 		if ! ldd "$TGTDIR/bin/$BINNAME"|grep -q 'statically linked'; then
 			echo -e "${cY}WARNING:${cZ} ${cW}$BINNAME${cZ} (crate ${cW}$CRATENAME${cZ}) did not come out statically linked!"
