Minor fix

diff --git a/build-scripts/build-llvm-and-clang b/build-scripts/build-llvm-and-clang
--- a/build-scripts/build-llvm-and-clang
+++ b/build-scripts/build-llvm-and-clang
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-for tool in readlink rm rmdir grep git date make cp date gcc find sha256sum cmake; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in readlink rm rmdir grep git date make cp date gcc find sha256sum; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 ( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBG=1; DEBUG=1; DBGCONFIGURE="$SHELL -x "; set -x; }
 LOCKFILE="${TMPDIR=/tmp}/${CURRABSPATH//\//_}${0##*/}.lock"
@@ -52,8 +52,9 @@ function show_help
 	echo -e "\t${cW}-p${cZ}"
 	echo -e "\t  Same as ${cW}-c${cZ} but also packages the Git repos in a .tar file after bundling them."
 	echo -e "\t  ${cY}NB:${cZ} requires ${cW}git tar xz${cZ}."
-	echo -e "\t${cW}-r${cZ}"
+	echo -e "\t${cW}-r${cZ} <moniker>"
 	echo -e "\t  Revives the repositories previously packaged with ${cW}-p${cZ}. Implies ${cW}-c${cZ}."
+	echo -e "\t  The moniker is typically a timestamp, e.g. packaged-${cW}\$TIMESTAMP${cZ}.tar."
 	echo -e "\t  ${cW}NB:${cZ} to be called from the directory which contains ${MEANDMYSELF}."
 	echo -e "\t  ${cY}NB:${cZ} requires a working ${cW}git${cZ}."
 	echo -e "\t${cW}-t${cZ} <targets> (default=${cW}$TARGETS${cZ})"
@@ -233,6 +234,10 @@ while getopts "h?b:BcCe:gGi:InoOPpr:t:TvxX" opt; do
 		;;
 	esac
 done
+# Check for availability of cmake if we're going to build
+if ((ONLYCHECKOUT==0)) && ((NOBUILD==0)); then
+	assert_tools cmake
+fi
 if ! (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
 	echo -e "${cR}ERROR:${cZ} Lock failed, PID $(cat "$LOCKFILE") [$LOCKFILE]" >&2
 	exit 1
