Adjusted some of the build scripts
- Updated version numbers
- Updated logic for cross-builds
- Added ccache support for build-ninja ...

diff --git a/build-scripts/build-dropbear b/build-scripts/build-dropbear
--- a/build-scripts/build-dropbear
+++ b/build-scripts/build-dropbear
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-CC_TO_USE=${CROSS_COMPILE}gcc
+CC_TO_USE=${CROSS_COMPILE}${CC:-gcc}
 ORIG_CC="$CC_TO_USE"
-for tool in rm rmdir dirname readlink file tempfile grep cut tee git date make "${CC_TO_USE}" wget tar sha256sum autoconf autoheader sed; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in rm rmdir dirname readlink file tempfile grep tee tr git date make "${CC_TO_USE}" wget tar sha256sum autoconf autoheader sed cut; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 ( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBG=1; DEBUG=1; DBGCONFIGURE="$SHELL -x "; set -x; }
 CROSS_COMPILE_PATH=${CROSS_COMPILE%/*}
@@ -14,7 +14,7 @@ LOCKFILE="${TMPDIR=/tmp}/${CURRABSPATH//\//_}${0##*/}.lock"
 MEANDMYSELF=${0##*/}
 ZLIBURL="http://zlib.net/zlib-1.2.11.tar.gz"
 ZLIBSHA256="c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1"
-DROPBEAR_RELEASE="DROPBEAR_2019.78"
+DROPBEAR_RELEASE="DROPBEAR_2020.80"
 DROPBEAR_GITREPO="https://github.com/mkj/dropbear.git"
 INSTALL_TO=${INSTALL_TO:-$HOME/bin/dropbear}
 BASEDIR="${BASEDIR:-$(pwd)}"
@@ -31,6 +31,12 @@ function show_help
 	echo -e "\t  Be verbose about the actions (lines get leading '${cB}[DBG]${cZ}' string)."
 	echo -e "\t${cW}-V${cZ} <dropbear-release-tag> ${cY}(if not given defaults to: $DROPBEAR_RELEASE)${cZ}"
 	echo -e "\t  Tag to build instead of hardcoded default."
+	echo -e "\t${cW}-x${cZ}"
+	echo -e "\t  Use ${cW}ccache${cZ} to speed up subsequent builds (${cY}NOT IMPLEMENTED!${cZ})."
+	echo -e "\t  ${cY}NB:${cZ} requires ${cW}ccache${cZ}."
+	if [[ -e "/etc/debian_version" ]]; then
+		echo -e "\t  ${cY}On Debian/Ubuntu:${cZ} requires package ${cW}ccache${cZ}."
+	fi
 	echo ""
 }
 
@@ -85,8 +91,20 @@ function show_time_diff
 	printf "$MSG\n" $(printf "%d:%02d" "$DIFF_MIN" "$DIFF_SEC")
 }
 
+function assert_tools
+{
+	local opt=$1
+	shift
+	for tool in "$@"; do
+		if ! type $tool > /dev/null 2>&1; then
+			echo -e "${cR}ERROR:${cZ} ${cY}-$opt${cZ} requires ${cW}$tool${cZ} which was not found!"
+			exit 1
+		fi
+	done
+}
+
 [[ "$1" == "--help" ]] && { show_help; exit 0; }
-while getopts "h?i:vV:" opt; do
+while getopts "h?i:vV:x" opt; do
 	case "$opt" in
 	h|\?)
 		show_help
@@ -100,6 +118,10 @@ while getopts "h?i:vV:" opt; do
 		;;
 	V)  [[ -n "$OPTARG" ]] || { echo -e "${cR}ERROR:${cZ} ${cY}-$opt${cZ} requires an argument." >&2; exit 1; }
 		DROPBEAR_RELEASE="$OPTARG"
+		;;
+	x)  USE_CCACHE=1
+		assert_tools "$opt" ccache
+		echo -e "${cY}Using ${cW}ccache${cY} to speed up subsequent builds${cZ}"
 		;;
 	*)
 		echo -e "${cY}WARNING:${cZ} unknown option '$opt'"
diff --git a/build-scripts/build-llvm-and-clang b/build-scripts/build-llvm-and-clang
--- a/build-scripts/build-llvm-and-clang
+++ b/build-scripts/build-llvm-and-clang
@@ -1,19 +1,26 @@
 #!/usr/bin/env bash
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-for tool in readlink rm rmdir grep git date make cp date gcc find sha256sum; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in readlink rm rmdir grep git date make cp date gcc find sha256sum tr; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 ( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBG=1; DEBUG=1; DBGCONFIGURE="$SHELL -x "; set -x; }
 LOCKFILE="${TMPDIR=/tmp}/${CURRABSPATH//\//_}${0##*/}.lock"
 MEANDMYSELF=${0##*/}
-LLVM_RELEASE="${LLVM_RELEASE:-llvmorg-9.0.1}"
+LLVM_RELEASE="${LLVM_RELEASE:-llvmorg-10.0.0}"
 BINUTILS_RELEASE="${BINUTILS_RELEASE:-binutils-2_34}"
 INSTALL_TO=${INSTALL_TO:-$HOME/bin/LLVM}
 BASEDIR="${BASEDIR:-$(pwd)}"
 TARGETS=all
-PROJECTS=clang,clang-tools-extra,compiler-rt,libcxx,libcxxabi,libunwind,openmp
+PROJECTS=clang,clang-tools-extra,compiler-rt,libcxx,libcxxabi,libunwind,openmp,lld,lldb
 BUILD_TYPE=MinSizeRel
 CMAKE_GENERATOR="Unix Makefiles"
 let NOOPTIONAL=0
+#PROJECTS=clang,clang-tools-extra,compiler-rt,libcxx,libcxxabi,libunwind,openmp,lld,lldb,polly
+# libedit-dev swig
+# https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/
+#-- Symbols (liblldb): exporting all symbols from the lldb namespace
+#-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
+#-- Could NOT find epydoc
+
 
 function show_help
 {
@@ -43,10 +50,15 @@ function show_help
 	echo -e "\t${cW}-n${cZ}"
 	echo -e "\t  Generate ${cW}Ninja${cZ} files (instead of ${cW}$CMAKE_GENERATOR${cZ})."
 	echo -e "\t  ${cY}NB:${cZ} requires ${cW}ninja${cZ}."
+	if [[ -e "/etc/debian_version" ]]; then
+		echo -e "\t  ${cY}On Debian/Ubuntu:${cZ} requires package ${cW}ninja-build${cZ}."
+	fi
 	echo -e "\t${cW}-o${cZ}"
 	echo -e "\t  Only build 'optional' components (i.e. binutils). Skips building Clang/LLVM."
 	echo -e "\t  ${cY}NB:${cZ} requires ${cW}bison flex makeinfo${cZ}."
-	echo -e "\t  ${cY}On Debian/Ubuntu:${cZ} requires packages ${cW}bison flex texinfo${cZ}."
+	if [[ -e "/etc/debian_version" ]]; then
+		echo -e "\t  ${cY}On Debian/Ubuntu:${cZ} requires packages ${cW}bison flex texinfo${cZ}."
+	fi
 	echo -e "\t${cW}-O${cZ}"
 	echo -e "\t  Do not build 'optional' components (i.e. binutils)."
 	echo -e "\t${cW}-p${cZ}"
@@ -66,7 +78,9 @@ function show_help
 	echo -e "\t${cW}-x${cZ}"
 	echo -e "\t  Use ${cW}ccache${cZ} to speed up subsequent builds."
 	echo -e "\t  ${cY}NB:${cZ} requires ${cW}ccache${cZ}."
-	echo -e "\t  ${cY}On Debian/Ubuntu:${cZ} requires package ${cW}ccache${cZ}."
+	if [[ -e "/etc/debian_version" ]]; then
+		echo -e "\t  ${cY}On Debian/Ubuntu:${cZ} requires package ${cW}ccache${cZ}."
+	fi
 	echo -e "\t${cW}-X${cZ}"
 	echo -e "\t  Use ${cW}clang${cZ} to build LLVM and clang (you need a recent clang!)."
 	echo -e "\t  ${cY}NB:${cZ} requires ${cW}clang clang++${cZ} (override with CLANG/CLANGPPLUS)."
diff --git a/build-scripts/build-musl b/build-scripts/build-musl
--- a/build-scripts/build-musl
+++ b/build-scripts/build-musl
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-CC_TO_USE=${CROSS_COMPILE}gcc
+CC_TO_USE=${CROSS_COMPILE}${CC:-gcc}
 ORIG_CC="$CC_TO_USE"
-for tool in rm rmdir dirname readlink file tempfile grep tee git date make "${CC_TO_USE}" gpg tar wc; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in rm rmdir dirname readlink file tempfile grep tee tr git date make "${CC_TO_USE}" gpg tar wc; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
-( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBGCONFIGURE="$SHELL -x "; set -x; }
+( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBG=1; DEBUG=1; DBGCONFIGURE="$SHELL -x "; set -x; }
 CROSS_COMPILE_PATH=${CROSS_COMPILE%/*}
 CROSS_COMPILE=${CROSS_COMPILE##*/}
 if [[ -n "$CROSS_COMPILE_PATH" ]]; then
@@ -35,6 +35,12 @@ function show_help
 	echo -e "\t  comma-separated list of architectures (default is to build both)."
 	echo -e "\t  ${cW}NOTE:${cZ} this can be useful on x86_64 to force only to build x86_64 or x86_32 instead of"
 	echo -e "\t  both."
+	echo -e "\t${cW}-x${cZ}"
+	echo -e "\t  Use ${cW}ccache${cZ} to speed up subsequent builds (${cY}NOT IMPLEMENTED!${cZ})."
+	echo -e "\t  ${cY}NB:${cZ} requires ${cW}ccache${cZ}."
+	if [[ -e "/etc/debian_version" ]]; then
+		echo -e "\t  ${cY}On Debian/Ubuntu:${cZ} requires package ${cW}ccache${cZ}."
+	fi
 	echo ""
 }
 
@@ -88,8 +94,20 @@ function show_time_diff
 	printf "$MSG\n" $(printf "%d:%02d" "$DIFF_MIN" "$DIFF_SEC")
 }
 
+function assert_tools
+{
+	local opt=$1
+	shift
+	for tool in "$@"; do
+		if ! type $tool > /dev/null 2>&1; then
+			echo -e "${cR}ERROR:${cZ} ${cY}-$opt${cZ} requires ${cW}$tool${cZ} which was not found!"
+			exit 1
+		fi
+	done
+}
+
 [[ "$1" == "--help" ]] && { show_help; exit 0; }
-while getopts "h?t:i:vV:" opt; do
+while getopts "h?t:i:vV:x" opt; do
 	case "$opt" in
 	h|\?)
 		show_help
@@ -107,6 +125,10 @@ while getopts "h?t:i:vV:" opt; do
 		;;
 	V)  [[ -n "$OPTARG" ]] || { echo -e "${cR}ERROR:${cZ} ${cY}-$opt${cZ} requires an argument." >&2; exit 1; }
 		MUSLLIBC_RELEASE="$OPTARG"
+		;;
+	x)  USE_CCACHE=1
+		assert_tools "$opt" ccache
+		echo -e "${cY}Using ${cW}ccache${cY} to speed up subsequent builds${cZ}"
 		;;
 	*)
 		echo -e "${cY}WARNING:${cZ} unknown option '$opt'"
diff --git a/build-scripts/build-ninja b/build-scripts/build-ninja
--- a/build-scripts/build-ninja
+++ b/build-scripts/build-ninja
@@ -1,14 +1,23 @@
 #!/usr/bin/env bash
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-for tool in rm rmdir dirname readlink file tempfile grep tee git date make gcc python install; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+CXX_TO_USE=${CROSS_COMPILE}${CXX:-g++}
+ORIG_CXX="$CXX_TO_USE"
+for tool in rm rmdir dirname readlink file tempfile grep tee tr git date make "${CXX_TO_USE}" install which; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
-( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBGCONFIGURE="$SHELL -x "; set -x; }
+( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBG=1; DEBUG=1; DBGCONFIGURE="$SHELL -x "; set -x; }
+CROSS_COMPILE_PATH=${CROSS_COMPILE%/*}
+CROSS_COMPILE=${CROSS_COMPILE##*/}
+if [[ -n "$CROSS_COMPILE_PATH" ]]; then
+	export PATH="$CROSS_COMPILE_PATH:$PATH"
+fi
 LOCKFILE="${TMPDIR=/tmp}/${CURRABSPATH//\//_}${0##*/}.lock"
 MEANDMYSELF=${0##*/}
-NINJA_RELEASE="v1.9.0"
-INSTALL_TO=${INSTALL_TO:-$HOME/bin/ninja}
+NINJA_RELEASE="v1.10.0"
+INSTALL_TO=${INSTALL_TO:-$HOME}
 BASEDIR="${BASEDIR:-$(pwd)}"
 CACHEDIR="$BASEDIR/cache"
+PYTHON_EXE=${PYTHON_EXE:-python}
+type "$PYTHON_EXE" > /dev/null 2>&1 || PYTHON_EXE=python3
 
 function show_help
 {
@@ -21,6 +30,12 @@ function show_help
 	echo -e "\t  Be verbose about the actions (lines get leading '${cB}[DBG]${cZ}' string)."
 	echo -e "\t${cW}-V${cZ} <ninja-release-tag> ${cY}(if not given defaults to: $NINJA_RELEASE)${cZ}"
 	echo -e "\t  Tag to build instead of hardcoded default."
+	echo -e "\t${cW}-x${cZ}"
+	echo -e "\t  Use ${cW}ccache${cZ} to speed up subsequent builds (${cY}NOT IMPLEMENTED!${cZ})."
+	echo -e "\t  ${cY}NB:${cZ} requires ${cW}ccache${cZ}."
+	if [[ -e "/etc/debian_version" ]]; then
+		echo -e "\t  ${cY}On Debian/Ubuntu:${cZ} requires package ${cW}ccache${cZ}."
+	fi
 	echo ""
 }
 
@@ -75,8 +90,20 @@ function show_time_diff
 	printf "$MSG\n" $(printf "%d:%02d" "$DIFF_MIN" "$DIFF_SEC")
 }
 
+function assert_tools
+{
+	local opt=$1
+	shift
+	for tool in "$@"; do
+		if ! type $tool > /dev/null 2>&1; then
+			echo -e "${cR}ERROR:${cZ} ${cY}-$opt${cZ} requires ${cW}$tool${cZ} which was not found!"
+			exit 1
+		fi
+	done
+}
+
 [[ "$1" == "--help" ]] && { show_help; exit 0; }
-while getopts "h?i:vV:" opt; do
+while getopts "h?i:vV:x" opt; do
 	case "$opt" in
 	h|\?)
 		show_help
@@ -89,7 +116,11 @@ while getopts "h?i:vV:" opt; do
 		((VERBOSE)) && echo -e "${cB}[DBG]${cZ} Enabling verbose run."
 		;;
 	V)  [[ -n "$OPTARG" ]] || { echo -e "${cR}ERROR:${cZ} ${cY}-$opt${cZ} requires an argument." >&2; exit 1; }
-		MUSLLIBC_RELEASE="$OPTARG"
+		NINJA_RELEASE="$OPTARG"
+		;;
+	x)  USE_CCACHE=1
+		assert_tools "$opt" ccache
+		echo -e "${cY}Using ${cW}ccache${cY} to speed up subsequent builds${cZ}"
 		;;
 	*)
 		echo -e "${cY}WARNING:${cZ} unknown option '$opt'"
@@ -119,7 +150,7 @@ trap 'rm -f "$LOCKFILE"; echo -e "'"${cW}INFO:${cZ}"' Removing the build directo
 echo -e "Configuring and building ${cW}$PRJ${cZ}"
 (
 	cd "$BUILDDIR" && \
-		$DBGCONFIGURE"$PRJSRCDIR/configure.py" --bootstrap && \
+		env CXX="${USE_CCACHE:+ccache }${CXX_TO_USE}" $DBGCONFIGURE"$PRJSRCDIR/configure.py" --bootstrap --verbose --with-python=$PYTHON_EXE && \
 		install -m 755 -vpsD $PRJNAME "$INSTALL_TO/bin/$PRJNAME"
 ) \
 	&& { trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT; } \
