Fixes to build-musl script

diff --git a/build-scripts/build-musl b/build-scripts/build-musl
--- a/build-scripts/build-musl
+++ b/build-scripts/build-musl
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-for tool in rm rmdir dirname readlink file tempfile grep tee git date make gcc gpg tar; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in rm rmdir dirname readlink file tempfile grep tee git date make gcc gpg tar wc; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 ( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBGCONFIGURE="$SHELL -x "; set -x; }
 LOCKFILE="${TMPDIR=/tmp}/${CURRABSPATH//\//_}${0##*/}.lock"
@@ -246,7 +246,7 @@ EOF
 
 MUSLGCC="$INSTALL_TO/musl-gcc"
 echo -e "${cW}INFO:${cZ} Preparing spec file for musl-gcc to build both 32-bit and 64-bit targets using -m32 and -m64 respectively"
-if [[ -n "$TARGETGIVEN" ]] && [[ -n "$ARCHARG" ]]; then
+if [[ -n "$TARGETGIVEN" ]] && [[ -n "$ARCHARG" ]] && (($(wc -w <<< $TARGETGIVEN) == 1)); then
 	ARCHARG=" $ARCHARG"
 else
 	ARCHARG=""
