More adjustments

diff --git a/build-scripts/build-dropbear b/build-scripts/build-dropbear
--- a/build-scripts/build-dropbear
+++ b/build-scripts/build-dropbear
@@ -1,9 +1,11 @@
 #!/usr/bin/env bash
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-for tool in rm rmdir dirname readlink file tempfile grep tee git date make gcc wget tar; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in rm rmdir dirname readlink file tempfile grep tee git date make gcc wget tar md5sum; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 ( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBGCONFIGURE="$SHELL -x "; set -x; }
 MEANDMYSELF=${0##*/}
+ZLIBURL="http://zlib.net/zlib-1.2.8.tar.gz"
+ZLIBMD5="44d667c142d7cda120332623eab69f40"
 DROPBEAR_RELEASE="DROPBEAR_2016.74"
 INSTALL_TO=${INSTALL_TO:-$HOME/bin/dropbear}
 BASEDIR="${BASEDIR:-$(pwd)}"
@@ -113,13 +115,29 @@ else
 	( echo -e "${cW}Building ${MUSLGCC##*/} now${cZ}"; cd "$CURRABSPATH" && ./build-musl )
 fi
 PATH=${MUSLGCC%/*}:$PATH
+SRCTARBALLDIR="$CACHEDIR/source-tarballs"
+[[ -d "$SRCTARBALLDIR" ]] || mkdir -p "$SRCTARBALLDIR"
+ZLIBPKG="$SRCTARBALLDIR/${ZLIBURL##*/}"
+if [[ -f "$ZLIBPKG" ]]; then
+	echo -e "${cW}${ZLIBURL##*/} already downloaded, using cached copy${cZ}"
+else
+	wget -nc -O "$ZLIBPKG" "$ZLIBURL" || curl -o "$ZLIBPKG" "$ZLIBURL" || { echo -e "${cR}ERROR:${cZ} failed to download $ZLIBURL"; exit 1; }
+fi
+echo "$ZLIBMD5  $ZLIBPKG"|md5sum -c ||  { echo -e "${cR}ERROR:${cZ} MD5 hash does not match!"; exit 1; }
+( rm -rf "$BUILDDIR"; mkdir -p "$BUILDDIR/zlib" )
+if echo -n "... unpacking zlib" && tar --strip-components=1 -C "$BUILDDIR/zlib" -xf "$ZLIBPKG" && mkdir -p "$BUILDDIR/zlib/tempinstall"; then
+	echo -e " ${cG}[OK]${cZ}"
+else
+	echo -e " ${cR}[failed]${cZ}"
+	exit 1
+fi
+
+
+
+
+
+
 exit 0
-
-TEMPDIR="$CURRABSPATH/cache"
-SRCPDIR="$CURRABSPATH/cache/source-tarballs"
-
-ZLIBURL="http://zlib.net/zlib-1.2.8.tar.gz"
-ZLIBPKG="$SRCPDIR/${ZLIBURL##*/}"
 
 [[ -d "$TEMPDIR" ]] || mkdir "$TEMPDIR" || { echo "FATAL: Could not create $TEMPDIR."; exit 1; }
 [[ -d "$SRCPDIR" ]] || mkdir "$SRCPDIR" || { echo "FATAL: Could not create $SRCPDIR."; exit 1; }
@@ -129,17 +147,8 @@ for i in musl zlib dropbear; do
 	[[ -d "$TEMPDIR/$i" ]] || mkdir "$TEMPDIR/$i" || { echo "FATAL: Could not create $TEMPDIR/$i."; exit 1; }
 done
 (
-	[[ -f "$ZLIBPKG" ]] || wget -O "$ZLIBPKG" "$ZLIBURL" || curl -o "$ZLIBPKG" "$ZLIBURL" || exit 1
-	echo "Unpacking zlib" && tar --strip-components=1 -C "$TEMPDIR/zlib" -xvf "$ZLIBPKG" && mkdir "$TEMPDIR/zlib/tempinstall" && \
 		echo "Unpacking dropbear" && tar --strip-components=1 -C "$TEMPDIR/dropbear" -xvf "$DRPBPKG"
 ) || { echo "FATAL: Could not unpack one of the required source packages. Check above output for clues."; exit 1; }
-echo "Configuring and building musl"
-(
-	cd "$TEMPDIR/musl" && \
-		./configure --disable-shared "--prefix=$TEMPDIR/musl/tempinstall" && \
-		make -j8 && \
-		make install
-) || { echo "FATAL: musl failed to build. Check above output for clues."; exit 1; }
 # Configure GCC for our purpose
 export CC="musl-gcc"
 export LDFLAGS="-Wl,--gc-sections"
