Refined Rust CLI build script, removed old
- The Rust CLI tool build script can now be controlled via
  two environment variables: NOCLEAN and NOSSL
  NB: in the previous commits I introduced the ability to
  selectively build only _some_ of the tools.
- Removed old tmate, tmux and nginx build scripts

diff --git a/build-scripts/build-rust-cli-tools b/build-scripts/build-rust-cli-tools
--- a/build-scripts/build-rust-cli-tools
+++ b/build-scripts/build-rust-cli-tools
@@ -4,7 +4,7 @@ TARGET=${TARGET:-x86_64-unknown-linux-musl}
 OPENSSL_REFNAME=${OPENSSL_REFNAME:-OpenSSL_1_1_1h}
 OPENSSL_ARCH=${OPENSSL_ARCH:-x86}
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-for tool in cp date dirname mkdir readlink tee grep ldd rustup sha256sum sort strip tar xz cargo; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in chmod cp date dirname mkdir readlink sed tee grep ldd rustup sha256sum sort strip tar xz cargo; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 test -d "$CURRABSPATH/cache" || mkdir -p "$CURRABSPATH/cache"
 TEMPDIR=${TEMPDIR:-"$(mktemp -dp "$CURRABSPATH/cache")"}
@@ -42,7 +42,7 @@ eva:NerdyPepper/eva
 exa:ogham/exa
 fastmod:facebookincubator/fastmod
 fd-find:fd:sharkdp/fd
-fddf:lib.rs/crates/fddf
+fddf://lib.rs/crates/fddf
 find-files:ff:vishaltelangre/ff
 funzzy:cristianoliveira/funzzy
 gfold:nickgerace/gfold
@@ -94,7 +94,7 @@ starship:starship/starship
 svgcleaner:RazrFalcon/svgcleaner
 tealdeer:tldr:dbrgn/tealdeer
 tiny:osa1/tiny
-tokei:lib.rs/crates/tokei
+tokei://lib.rs/crates/tokei
 treesum:anderejd/treesum
 typeracer:ttyperacer/terminal-typeracer
 vcprompt:sscherfke/rust-vcprompt
@@ -108,7 +108,7 @@ wool:grapegrip/wool
 xsv:BurntSushi/xsv
 yadf:jRimbault/yadf
 zenith:bvaisvil/zenith
-zoxide:lib.rs/crates/zoxide
+zoxide://lib.rs/crates/zoxide
 zrs:fauxfaux/zrs
 "
 
@@ -234,7 +234,8 @@ function strip_and_store_binaries
 {
 	local SRCDIR="$1"
 	local NOWDATE=$(date +"%Y-%m-%dT%H-%M-%S")
-	local TGTDIR="$SRCDIR/${NOWDATE}_rust-cli-tools" # output folder ... inside temporary folder until we're successful
+	local BASENAME="${NOWDATE}_rust-cli-tools"
+	local TGTDIR="$SRCDIR/$BASENAME" # output folder ... inside temporary folder until we're successful
 	( cd "${TGTDIR%/*}"; set -x; mkdir -p "${TGTDIR##*/}"/{stripped,unstripped} ) || { echo -e "${cR}ERROR:${cZ} failed to create staging area for output"; exit 1; }
 	( set -x; cp -a "$SRCDIR/bin"/* "$TGTDIR/unstripped/" ) || { echo -e "${cR}ERROR:${cZ} failed to copy unstripped binaries"; exit 1; }
 	# Strip binaries into different path
@@ -248,21 +249,42 @@ function strip_and_store_binaries
 	find "$TGTDIR" -type f -executable -printf '%P\n'|sort|while read fname; do
 		( cd "$TGTDIR"; set -x; sha256sum $fname ) || { echo -e "${cR}ERROR:${cZ} failed to compute hash for ${cW}$fname${cZ}"; exit 1; }
 	done | tee "$TGTDIR/SHA256SUMS"
-	cargo install --root "$SRCDIR" --list|tee "$TGTDIR/manifest.txt"
-	( CURRDIR="$(pwd)"; set -x; tar -cJvf "$CURRDIR/${NOWDATE}_rust-cli-tools.txz" -C "$TGTDIR" . ) || { echo -e "${cR}ERROR:${cZ} failed to package built binaries"; exit 1; }
-	( CURRDIR="$(pwd)"; set -x; sha256sum "$CURRDIR/${NOWDATE}_rust-cli-tools.txz" | tee "$CURRDIR/${NOWDATE}_rust-cli-tools.txz.SHA256SUM" ) || { echo -e "${cR}ERROR:${cZ} failed to compute hash of package"; exit 1; }
+	# And separate them for stripped/unstripped subfolder
+	grep -P '\Wstripped/' "$TGTDIR/SHA256SUMS"|sed -e 's|stripped/||g'|tee "$TGTDIR/stripped/SHA256SUMS"
+	grep -P '\Wunstripped/' "$TGTDIR/SHA256SUMS"|sed -e 's|unstripped/||g'|tee "$TGTDIR/unstripped/SHA256SUMS"
+	local TARBALL="$BASENAME-$(uname -m)"
+	# Retrieve version info of the tools we just built
+	cargo install --root "$SRCDIR" --list|tee "$TGTDIR/manifest.txt"|tee "$(pwd)/$TARBALL.manifest.txt"
+	cat > "$TGTDIR/install.sh" <<-EOF
+	#!/usr/bin/env bash
+	[[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
+	for tool in dirname find readlink sha256sum install; do type \$tool > /dev/null 2>&1 || { echo -e "\${cR}ERROR:\${cZ} couldn't find '\$tool' which is required by this script."; exit 1; }; done
+	pushd \$(dirname \$0) > /dev/null; CURRABSPATH=\$(readlink -nf "\$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
+	[[ -d "\$CURRABSPATH/unstripped" ]] && SRCDIR="unstripped"
+	[[ -d "\$CURRABSPATH/stripped" ]] && SRCDIR="stripped"
+	( cd "\$SRCDIR"; set -x; sha256sum -c SHA256SUMS ) || { echo -e "\${cR}ERROR:\${cZ} failed to validate integrity of the binaries in \$(pwd)."; exit 1; }
+	( set -x; sudo install -g root -o root -m 0755 -p -v -t /usr/local/bin \$(find "\$CURRABSPATH/\$SRCDIR" -type f -executable -printf "\$SRCDIR/%P\n") )
+	EOF
+	chmod +x "$TGTDIR/install.sh"
+	( CURRDIR="$(pwd)"; set -x; tar -cJvf "$CURRDIR/$TARBALL.txz" -C "$SRCDIR" "$BASENAME" ) || { echo -e "${cR}ERROR:${cZ} failed to package built binaries"; exit 1; }
+	( CURRDIR="$(pwd)"; set -x; sha256sum "$CURRDIR/$TARBALL.txz" | tee "$CURRDIR/$TARBALL.txz.SHA256SUM" ) || { echo -e "${cR}ERROR:${cZ} failed to compute hash of package"; exit 1; }
+	TARBALL="$TARBALL.stripped"
+	( CURRDIR="$(pwd)"; set -x; tar -cJvf "$CURRDIR/$TARBALL.txz" -C "$SRCDIR" "$BASENAME/stripped" "$BASENAME/install.sh" $(find "$SRCDIR" -type f \( -name 'manifest.txt' -o -name 'warnings.txt' \) -printf '%P\n') ) || { echo -e "${cR}ERROR:${cZ} failed to package built binaries"; exit 1; }
+	( CURRDIR="$(pwd)"; set -x; sha256sum "$CURRDIR/$TARBALL.txz" | tee "$CURRDIR/$TARBALL.txz.SHA256SUM" ) || { echo -e "${cR}ERROR:${cZ} failed to compute hash of package"; exit 1; }
 }
 
 # Ensure we clean up after ourselves in any case
 let TIME_START=$(date +%s)
 trap 'echo "Removing temporary directory"; ( set -x; rm -rf "'$TEMPDIR'" ); trap - INT TERM EXIT; exit $?' INT TERM EXIT
-echo -e "${cW}INFO:${cZ} building OpenSSL"
-openssl_build || exit 1
+if [[ -z "NOSSL" ]]; then
+	echo -e "${cW}INFO:${cZ} building OpenSSL"
+	openssl_build || exit 1
+fi
 for tool in $SIMPLE_INSTALLS; do
 	simple_install "$tool" "$TEMPDIR" "$@"
 done
 strip_and_store_binaries "$TEMPDIR"
-# Clean exit
-#trap - INT TERM EXIT
+# Clean exit, or leave everything in place if NOCLEAN environment variable was set
+[[ -n "$NOCLEAN" ]] && trap - INT TERM EXIT
 let TIME_END=$(date +%s)
 show_time_diff $TIME_START $TIME_END "Overall runtime: %s (m:ss) with $PM parallel job(s)"
