Removing support for old Clang/LLVM versions (simply use older revisions if needed). Bumped version of CMake to build.

diff --git a/build-scripts/build-llvm-and-clang b/build-scripts/build-llvm-and-clang
--- a/build-scripts/build-llvm-and-clang
+++ b/build-scripts/build-llvm-and-clang
@@ -1,16 +1,18 @@
 #!/usr/bin/env bash
 [[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
-for tool in readlink rm rmdir grep awk cut tee tar bzip2 sha1sum git date make cp date gcc find sha256sum; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
+for tool in readlink rm rmdir grep awk cut tee tar xz sha1sum git date make cp date gcc find sha256sum cmake; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
 pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
 ( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBG=1; DEBUG=1; DBGCONFIGURE="$SHELL -x "; set -x; }
 LOCKFILE="${TMPDIR=/tmp}/${CURRABSPATH//\//_}${0##*/}.lock"
 MEANDMYSELF=${0##*/}
-LLVM_RELEASE="${LLVM_RELEASE:-llvmorg-8.0.1}"
+LLVM_RELEASE="${LLVM_RELEASE:-llvmorg-9.0.0}"
 BINUTILS_RELEASE="${BINUTILS_RELEASE:-binutils-2_32}"
 INSTALL_TO=${INSTALL_TO:-$HOME/bin/LLVM}
 BASEDIR="${BASEDIR:-$(pwd)}"
-TARGETS="Native"
+TARGETS=all
+PROJECTS=clang,clang-tools-extra,compiler-rt,libcxx,libcxxabi,libunwind,openmp
 BUILD_TYPE=MinSizeRel
+CMAKE_GENERATOR="Unix Makefiles"
 let NOOPTIONAL=0
 PAYLOAD=""
 
@@ -20,7 +22,7 @@ function show_help
 	echo -e "\t${cW}-h | -?${cZ}"
 	echo -e "\t  Show this help"
 	echo -e "\t${cW}-b${cZ} <RelWithDebInfo|Release|MinSizeRel|Debug>"
-	echo -e "\t  Pick a build type. Can also be done by setting ${cW}BUILD_TYPE${cZ}."
+	echo -e "\t  Pick a build type. Can also be done by setting env. variable ${cW}BUILD_TYPE${cZ}."
 	echo -e "\t  This defaults to ${cW}BUILD_TYPE=${BUILD_TYPE}${cZ}."
 	echo -e "\t${cW}-B${cZ}"
 	echo -e "\t  Do not actually build anything, but check out and prepare build directory."
@@ -28,6 +30,8 @@ function show_help
 	echo -e "\t  Only check out updates from upstream, then exit."
 	echo -e "\t${cW}-C${cZ}"
 	echo -e "\t  Do not check out from the upstream repository."
+	echo -e "\t${cW}-e${cZ} <projects> (default=${cW}$PROJECTS${cZ})"
+	echo -e "\t  Enable projects (comma/semi-colon-separated list) for LLVM/Clang build."
 	echo -e "\t${cW}-g${cZ}"
 	echo -e "\t  Garbage collect after checkout."
 	echo -e "\t${cW}-G${cZ}"
@@ -37,26 +41,28 @@ function show_help
 	echo -e "\t  This defaults to ${cW}INSTALL_TO=${INSTALL_TO}${cZ}."
 	echo -e "\t${cW}-I${cZ}"
 	echo -e "\t  Do not install after building the targets."
+	echo -e "\t${cW}-n${cZ}"
+	echo -e "\t  Generate ${cW}Ninja${cZ} files (instead of ${cW}$CMAKE_GENERATOR${cZ})."
 	echo -e "\t${cW}-o${cZ}"
 	echo -e "\t  Only build 'optional' components (i.e. binutils). Skips building Clang/LLVM."
 	echo -e "\t${cW}-O${cZ}"
 	echo -e "\t  Do not build 'optional' components (i.e. binutils)."
 	echo -e "\t${cW}-p${cZ}"
-	echo -e "\t  Same as ${cW}-c${cZ} but also packages the Git repos in a .tgz file."
+	echo -e "\t  Same as ${cW}-c${cZ} but also packages the Git repos in a .txz file."
 	echo -e "\t${cW}-P${cZ}"
 	echo -e "\t  Unpack payload script instead of a pre-existing one in this folder."
 	echo -e "\t  ${cW}NOTE:${cZ} normally the payload script is only used if none exists already."
 	echo -e "\t${cW}-r${cZ}"
 	echo -e "\t  Revives the repositories previously packaged with ${cW}-p${cZ}. Implies ${cW}-c${cZ}."
 	echo -e "\t  ${cW}NB:${cZ} to be called from the directory which contains ${MEANDMYSELF}."
-	echo -e "\t${cW}-t${cZ} <targets> (default=Native)"
-	echo -e "\t  Specify the target architectures for LLVM/Clang."
+	echo -e "\t${cW}-t${cZ} <targets> (default=${cW}$TARGETS${cZ})"
+	echo -e "\t  Specify the target architectures (comma/semi-colon-separated list) for LLVM/Clang."
 	echo -e "\t${cW}-T${cZ}"
 	echo -e "\t  Run tests after building, but before installing LLVM and Clang."
 	echo -e "\t${cW}-v${cZ}"
 	echo -e "\t  Be verbose about the actions (lines get leading '${cB}[DBG]${cZ}' string)."
 	echo -e "\t${cW}-x${cZ}"
-	echo -e "\t  Use ${cW}ccache${cZ} to speed up builds."
+	echo -e "\t  Use ${cW}ccache${cZ} to speed up subsequent builds."
 	echo -e "\t${cW}-X${cZ}"
 	echo -e "\t  Use ${cW}clang${cZ} to build LLVM and clang (you need a recent clang!)."
 	echo ""
@@ -158,7 +164,7 @@ function prepare_tool
 }
 
 [[ "$1" == "--help" ]] && { show_help; exit 0; }
-while getopts "h?b:BcCgGi:InoOPprt:TvxX" opt; do
+while getopts "h?b:BcCe:gGi:InoOPprt:TvxX" opt; do
 	case "$opt" in
 	h|\?)
 		show_help
@@ -178,6 +184,9 @@ while getopts "h?b:BcCgGi:InoOPprt:TvxX" opt; do
 		NOCHECKOUT=1
 		echo -e "${cY}Skipping checkout${cZ}"
 		;;
+	e)  [[ -n "$OPTARG" ]] || { echo -e "${cR}ERROR:${cZ} ${cY}-$opt${cZ} requires an argument." >&2; exit 1; }
+		PROJECTS="$OPTARG"
+		;;
 	g)  GARBAGECOLLECT=1
 		;;
 	G)  GARBAGECOLLECT=1
@@ -188,7 +197,8 @@ while getopts "h?b:BcCgGi:InoOPprt:TvxX" opt; do
 		;;
 	I)  NOINSTALL=1
 		;;
-	n)  ;;
+	n)  CMAKE_GENERATOR="Ninja"
+		;;
 	o)  ((NOOPTIONAL)) && { echo -e "${cR}ERROR:${cZ} ${cY}-$opt${cZ} and ${cY}-O${cZ} are mutually exclusive."; exit 1; }
 		ONLYOPTIONAL=1
 		NOOPTIONAL=0
@@ -203,8 +213,8 @@ while getopts "h?b:BcCgGi:InoOPprt:TvxX" opt; do
 		;;
 	p)  ((NOCHECKOUT)) && { echo -e "${cR}ERROR:${cZ} ${cY}-C${cZ} and ${cY}-p${cZ}/${cY}-c${cZ} are mutually exclusive."; exit 1; }
 		ONLYCHECKOUT=1
-		PACKAGEGITGZ=1
-		echo "Doing only a checkout and then packaging bare clones into .tbz (requires tar+bzip2)."
+		PACKAGEGITXZ=1
+		echo "Doing only a checkout and then packaging bare clones into .tbz (requires tar+xz)."
 		;;
 	r)  ((NOCHECKOUT)) || ONLYCHECKOUT=1
 		REVIVEPKG=1
@@ -232,21 +242,6 @@ if ! (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
 	exit 1
 fi
 trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
-# Newer versions of LLVM & Clang abolished the old './configure && make' in favor of CMake
-if [[ "${LLVM_RELEASE:0:8}" == "llvmorg-" ]] || ((${LLVM_RELEASE##*_} > 36)); then
-	if ((ONLYCHECKOUT == 0)); then
-		prepare_tool cmake
-		let CMAKE_BUILD=1
-	fi
-	TARGETS="Native"
-else
-	if ((ONLYCHECKOUT == 0)); then
-		let CMAKE_BUILD=0
-		echo -e "${cW}INFO:${cZ} preparing for build using autotools"
-	fi
-	TARGETS="x86,x86_64"
-fi
-CMAKE_GENERATOR="Unix Makefiles"
 
 echo -e "\tWorking directory: $BASEDIR"
 let PM=$(grep -c processor /proc/cpuinfo)
@@ -273,35 +268,37 @@ if ((USE_CLANG)); then
 		echo -e "${cR}ERROR:${cZ} couldn't find 'CC=$CC' or 'CXX=$CXX'."
 		exit 1
 	fi
-	CMAKE_C_COMPILER_ID=Clang
-	CMAKE_CXX_COMPILER_ID=Clang
-	CMAKE_C_COMPILER_VERSION=$($CC --version|grep -oP 'clang version (\d+\.)+\d+'|grep -oP '(\d+\.)+\d+$')
-	CMAKE_CXX_COMPILER_VERSION=$($CXX --version|grep -oP 'clang version (\d+\.)+\d+'|grep -oP '(\d+\.)+\d+$')
-	CMAKE_C_STANDARD_COMPUTED_DEFAULT=11
-	CMAKE_CXX_STANDARD_COMPUTED_DEFAULT=11
 else
 	CC="gcc"
 	CXX="g++"
-	CMAKE_C_COMPILER_ID=GNU
-	CMAKE_CXX_COMPILER_ID=GNU
-	CMAKE_C_COMPILER_VERSION=$($CC --version|grep -oP '(\d+\.)+\d+(\s+\d+)?$'|awk '{print $1}')
-	CMAKE_CXX_COMPILER_VERSION=$($CXX --version|grep -oP '(\d+\.)+\d+(\s+\d+)?$'|awk '{print $1}')
-	CMAKE_C_STANDARD_COMPUTED_DEFAULT=11
-	CMAKE_CXX_STANDARD_COMPUTED_DEFAULT=11
 fi
-[[ -n "$CMAKE_C_COMPILER_VERSION" ]] || { echo -e "${cR}ERROR:${cZ} CMAKE_C_COMPILER_VERSION is empty."; exit 1; }
-[[ -n "$CMAKE_CXX_COMPILER_VERSION" ]] || { echo -e "${cR}ERROR:${cZ} CMAKE_CXX_COMPILER_VERSION is empty."; exit 1; }
 let TIME_GIT=$(date +%s)
 if ((ONLYCHECKOUT==0)) && ((NOBUILD==0)); then
 	((VERBOSE)) && echo -e "${cB}[DBG]${cZ} Doing build for $TARGETS into $INSTALL_TO."
 	if [[ -d "$BASEDIR/build/llvm" ]]; then
 		if ((ONLYOPTIONAL == 0)); then
 			pushd "$BASEDIR/build/llvm" || { echo -e "${cR}ERROR:${cZ} could not ${cW}pushd${cZ}."; exit 1; }
-			if (( CMAKE_BUILD )); then
-				( set -x; cmake ${TRACE:+--trace} -G "$CMAKE_GENERATOR" ${USE_CLANG:+-DCMAKE_C_FLAGS=-Wno-unused-command-line-argument} ${USE_CLANG:+-DCMAKE_CXX_FLAGS=-Wno-unused-command-line-argument} -DCMAKE_C_STANDARD_COMPUTED_DEFAULT="$CMAKE_C_STANDARD_COMPUTED_DEFAULT" -DCMAKE_CXX_STANDARD_COMPUTED_DEFAULT="$CMAKE_CXX_STANDARD_COMPUTED_DEFAULT" -DCMAKE_C_COMPILER_ID="$CMAKE_C_COMPILER_ID" -DCMAKE_CXX_COMPILER_ID="$CMAKE_CXX_COMPILER_ID" -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER_VERSION="$CMAKE_C_COMPILER_VERSION" -DCMAKE_CXX_COMPILER_VERSION="$CMAKE_CXX_COMPILER_VERSION" ${USE_CCACHE:+-DCMAKE_C_COMPILER_LAUNCHER=ccache} ${USE_CCACHE:+-DCMAKE_CXX_COMPILER_LAUNCHER=ccache} -DCMAKE_INSTALL_PREFIX="$INSTALL_TO" -DLLVM_BUILD_DOCS=OFF -DLLVM_ENABLE_DOXYGEN=OFF -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DLLVM_TARGETS_TO_BUILD="${TARGETS//,/;}" "$BASEDIR/llvm" ) || { echo -e "${cR}ERROR:${cZ}  ${cW}cmake${cZ} failed."; exit 1; }
-			else
-				( set -x; env CC="${USE_CCACHE:+ccache }$CC" CXX="${USE_CCACHE:+ccache }$CXX" "$BASEDIR/llvm/configure" --prefix=$INSTALL_TO --disable-docs --disable-doxygen --enable-optimized --enable-targets=$TARGETS ) || { echo -e "${cR}ERROR:${cZ}  ${cW}./configure${cZ} failed."; exit 1; }
-			fi
+			( set -x; \
+				cmake ${TRACE:+--trace} ${TRACE:--Wno-dev} -G "$CMAKE_GENERATOR" \
+				${USE_CLANG:+-DCMAKE_C_FLAGS=-Wno-unused-command-line-argument} \
+				${USE_CLANG:+-DCMAKE_CXX_FLAGS=-Wno-unused-command-line-argument} \
+				${CMAKE_C_STANDARD_COMPUTED_DEFAULT:+-DCMAKE_C_STANDARD_COMPUTED_DEFAULT=$CMAKE_C_STANDARD_COMPUTED_DEFAULT} \
+				${CMAKE_CXX_STANDARD_COMPUTED_DEFAULT:+-DCMAKE_CXX_STANDARD_COMPUTED_DEFAULT=$CMAKE_CXX_STANDARD_COMPUTED_DEFAULT} \
+				${CMAKE_C_COMPILER_ID:+-DCMAKE_C_COMPILER_ID=$CMAKE_C_COMPILER_ID} \
+				${MAKE_CXX_COMPILER_ID:+-DCMAKE_CXX_COMPILER_ID=$CMAKE_CXX_COMPILER_ID} \
+				${CC:+-DCMAKE_C_COMPILER=$CC} \
+				${CXX:+-DCMAKE_CXX_COMPILER=$CXX} \
+				${CMAKE_C_COMPILER_VERSION:+-DCMAKE_C_COMPILER_VERSION=$CMAKE_C_COMPILER_VERSION} \
+				${CMAKE_CXX_COMPILER_VERSION:+-DCMAKE_CXX_COMPILER_VERSION=$CMAKE_CXX_COMPILER_VERSION} \
+				${USE_CCACHE:+-DLLVM_CCACHE_BUILD=ccache} \
+				${VERBOSE:+-DCMAKE_VERBOSE_MAKEFILE=ON} \
+				-DLLVM_ENABLE_PROJECTS="${PROJECTS//,/;}" \
+				-DCMAKE_INSTALL_PREFIX="$INSTALL_TO" \
+				-DLLVM_BUILD_DOCS=OFF \
+				-DLLVM_ENABLE_DOXYGEN=OFF \
+				-DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
+				-DLLVM_TARGETS_TO_BUILD="${TARGETS//,/;}" \
+				"$BASEDIR/llvm/llvm" ) || { echo -e "${cR}ERROR:${cZ}  ${cW}cmake${cZ} failed."; exit 1; }
 			let TIME_CONFIGURE=$(date +%s)
 			# FIXME/TODO: add _options_ to enable optimizations and disable assertions somehow?! (i.e. don't hardcode them)
 			( set -x; make -j$PM ENABLE_OPTIMIZED=1 DISABLE_ASSERTIONS=1 ${DBG:+TOOL_VERBOSE=1} )  || { echo -e "${cR}ERROR:${cZ}  ${cW}make${cZ} failed."; exit 1; }
@@ -310,6 +307,12 @@ if ((ONLYCHECKOUT==0)) && ((NOBUILD==0)); then
 				( set -x; make -j$PM test )  || { echo -e "${cR}ERROR:${cZ}  ${cW}make clang-test${cZ} failed."; exit 1; }
 			fi
 			if ((NOINSTALL == 0)); then
+				if [[ -d "$INSTALL_TO" ]]; then
+					OLD_INSTALL_TO="backup-${INSTALL_TO##*/}-$(date -r "$INSTALL_TO" +"%Y-%m-%dT%H-%M-%S")"
+					echo -e "${cW}NOTE:${cZ} $INSTALL_TO exists, renaming it to $OLD_INSTALL_TO."
+					mv "$INSTALL_TO" "${INSTALL_TO%/*}/$OLD_INSTALL_TO" || { echo -e "${cR}ERROR:${cZ} failed to move $INSTALL_TO out of the way."; exit 1; }
+					trap 'rm -f "$LOCKFILE"; echo -e "'"${cW}INFO:${cZ}"' Moving back your previous LLVM from '$OLD_INSTALL_TO' due to signal"; rm -rf "'$INSTALL_TO'"; mv "'${INSTALL_TO%/*}/$OLD_INSTALL_TO'" "'$INSTALL_TO'"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
+				fi
 				( set -x; make -j$PM ENABLE_OPTIMIZED=1 DISABLE_ASSERTIONS=1 ${DBG:+TOOL_VERBOSE=1} install )  || { echo -e "${cR}ERROR:${cZ}  ${cW}make install${cZ} failed."; exit 1; }
 			fi
 			popd || { echo -e "${cR}ERROR:${cZ} could not ${cY}popd${cZ}."; exit 1; }
@@ -334,7 +337,7 @@ fi
 if ((ONLYCHECKOUT==1)) || ((NOBUILD==1)); then
 	show_time_diff $TIME_START $TIME_GIT      "Git operations took: %s"
 fi
-if ((PACKAGEGITGZ==1)); then
+if ((PACKAGEGITXZ==1)); then
 	TIMESTAMP=$(date +%Y-%m-%dT%H-%M-%S)
 	TARNAME="packaged-${TIMESTAMP}-LLVM+binutils.tbz"
 	UNPACKER="unpack-$TIMESTAMP-LLVM"
@@ -350,18 +353,13 @@ if ((PACKAGEGITGZ==1)); then
 		echo -e "#!/usr/bin/env bash\nT=\"$TARNAME\"\nD=\"$TIMESTAMP-LLVM\"\nR=\"$REVIVE\"\nU=\"$UNPACKER\"\necho \"Unpacking \$T into ./\$D \$( [[ \"x\$1\" == \"x-c\" ]] && echo \"and removing archive plus unpacker upon success\" )\"\nmkdir \"./\$D\" && tar -C \"./\$D\" -xjf \"./\$T\" && ( cd \"./\$D\" && [[ -x \$R ]] && \$R && rm -f \$R )\n[[ \"x\$1\" == \"x-c\" ]] && { echo \"Also removing \$U and \$T\"; rm -f \"./\$U\" \"./\$T\"; }" \
 			| tee "./$UNPACKER" > /dev/null && chmod +x "./$UNPACKER"
 	)
-	let TIME_TGZ=$(date +%s)
-	show_time_diff $TIME_GIT $TIME_TGZ                      "Packaging took:      %s"
+	let TIME_TXZ=$(date +%s)
+	show_time_diff $TIME_GIT $TIME_TXZ                      "Packaging took:      %s"
 fi
 let TIME_END=$(date +%s)
 if ((ONLYCHECKOUT==0)) && ((NOBUILD==0)); then
 	if ((ONLYOPTIONAL == 0)); then
-		if (( CMAKE_BUILD )); then
-			show_time_diff $TIME_GIT $TIME_CONFIGURE        "CMake       took:    %s"
-		else
-			show_time_diff $TIME_GIT $TIME_CONFIGURE        "./configure took:    %s"
-			show_time_diff $TIME_CONFIGURE $TIME_MAKE       "GNU make took:       %s"
-		fi
+		show_time_diff $TIME_GIT $TIME_CONFIGURE        "CMake       took:    %s"
 		if ((NOINSTALL == 0)); then
 			show_time_diff $TIME_MAKE $TIME_INSTALL         "Installation took:   %s"
 		fi
